HHS/simpler-grants-pdf-builder

CHANGELOG.md, README.md, bloom_nofos/bloom_nofos/static/theme-orientation-portrait.css, bloom_nofos/nofos/templatetags/utils/__init__.py, bloom_nofos/nofos/test_templatetags.py
This PR: fixes table widths for step 4, and makes some updates to the README.
We have some general rules for table sizes: 
- tables with 3 or more columns are full-width, OR tables with over 100 words
However, for Step 4, we have more specific ideas:
- "Criterion" tables should be col-width
- All other tables should be full-width
This PR fixes our table rules for step 4 to make that work.
|    only 2 tables here are full-width    |    all tables full-width except our 2 criterion tables   |
|   <img width="241" alt="Screenshot 2024-10-24 at 1 59 20 PM" src="https://github.com/user-attachments/assets/f0752b72-b4e3-4c3a-abd6-a83a37d26902">    |   <img width="241" alt="Screenshot 2024-10-24 at 1 58 40 PM" …
=> Make sure criterion tables are small but other step 4 tables are large

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/bloom_nofos/static/theme-orientation-portrait.css, bloom_nofos/nofos/templatetags/replace_unicode_with_icon.py, bloom_nofos/nofos/test_nofo.py
This PR fixes the layout of the application checkbox tables.
Here's the issue.
We have this pretty complex checkbox-style of table and we don't want long text lines to go back to the start of the `<td>`. We want to style them so they are more like bullets.
So, for example:
```
◻ item 1
◻ item 2
◻ item 3 a really long item about
another thing
◻ item 4
```
We want to avoid a situation where "another" starts on the same vertical line as the checkboxes.
What we want is this:
```
◻ item 1
◻ item 2
◻ item 3 a really long item about
another thing
◻ item 4
```
In order to do this in CSS, we have to add some structure, like a flexbox.
Unfortunately, you can't just add flexbox styling to a table cell, because the table cell already has a display: of `table-cell`. If you make them flexboxes, the …
=> Fix styling for the application checkbox tables

CHANGELOG.md, bloom_nofos/nofos/forms.py, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/templatetags/replace_unicode_with_icon.py
1. Uses the `agency` not the `subagency` on the cover page for HRSA
2. Allow users to remove Subagency and Subagency 2
3.  Reverses the links on the NOFO view page
This is something Betty asked us for: 
> Change the name under the HRSA logo from Division of Maternal and Child Health Workforce Development to “Maternal and Child Health Bureau”
|  <img width="194" alt="Screenshot 2024-10-25 at 1 07 40 PM" src="https://github.com/user-attachments/assets/603fc7b1-478f-4cd5-a8ce-4ba605107c7e">   |   <img width="194" alt="Screenshot 2024-10-25 at 1 06 54 PM" src="https://github.com/user-attachments/assets/770e2fbd-56ab-47b1-95fe-450b9fdf0edb">  |
If they were ever entered, we don't let users delete them. Ultimately, we don't have a …
=> More HRSA updates

CHANGELOG.md, bloom_nofos/nofos/templatetags/replace_unicode_with_icon.py
This PR does 4 things:
1. Uses the `agency` not the `subagency` on the cover page for HRSA
2. "Other required forms" is a sublist heading in application checklist
3. Allow users to remove Subagency and Subagency 2
4.  Reverses the links on the NOFO view page
This is something Betty asked us for: 
> Change the name under the HRSA logo from Division of Maternal and Child Health Workforce Development to “Maternal and Child Health Bureau”
|  <img width="194" alt="Screenshot 2024-10-25 at 1 07 40 PM" src="https://github.com/user-attachments/assets/603fc7b1-478f-4cd5-a8ce-4ba605107c7e">   |   <img width="194" alt="Screenshot 2024-10-25 at 1 06 54 PM" src="https://github.com/user-attachments/assets/770e2fbd-56ab-47b1-95fe-450b9fdf0edb">  |
But normally …
=> Hrsa fixes 2

CHANGELOG.md, pyproject.toml
Nothing major in here, but we've added a lot of small changes, so let's up the version.
From the CHANGELOG:
```
- Convert 'Heading 7' styles from Word
- Add cover image for CDC-RFA-DD-25-0157
- Add cover image for CDC-RFA-DP-25-0024
- Add cover image for HRSA-25-068
- Add cover image for HRSA-25-025
- Add cover image for HRSA-25-027
- Allow users to remove subagency and subagency 2
- HRSA tagline is now HRSA blue!
- Show subagency under the logo on the small image page, not subagency 2
- For HRSA, show the agency, not the subagency
- Reimporting a NOFO that already has a cover image won't replace the image
- Change heading links on NOFO view page
- "Other required forms" and "attachments" are sublist headings in application table
- Restructure HTML in the Application Checklists for better …
```
=> Bump version to 1.29.0

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-blue.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc.css
1. removes stroke styling for the CDC logo. 
2. adds some left padding to callout box lists
3. small CSS changes that let us manually fix application table checkbox lists
I had added the stroke styling to fix what looked like a font rendering issue. But actually it was overcorrecting for a CSS rule that I didn't need, so now all the stroke rules are gone.
|   <img width="436" alt="Screenshot 2024-10-28 at 4 53 19 PM" src="https://github.com/user-attachments/assets/fda0b9bb-5b64-4116-828f-e67598ccb6dc">    |    <img width="436" alt="Screenshot 2024-10-28 at 4 53 28 PM" src="https://github.com/user-attachments/assets/a225ff36-0ed2-4319-9e51-c83ccb02e8bb">   |
| <img width="436" alt="Screenshot …
=> Remove stroke in CDC logo, add left padding to callout lists, manual CSS fixes for application table cells

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-opdiv-acf-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-acl-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-aspr-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-blue.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-dop.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-orr.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cms-blue.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cms-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-hrsa-blue.css, bloom_nofos/bloom_nofos/static/theme-opdiv-hrsa-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-ihs.css
This PR adds a bottom border to application checklist table cells that:
- have a checkbox
- are not sublists
Hopefully this styling change is the final one!
|   <img width="618" alt="Screenshot 2024-10-29 at 12 17 53 PM" src="https://github.com/user-attachments/assets/b03bf9ae-68ad-4091-9000-1b0b19882c06">    |  <img width="618" alt="Screenshot 2024-10-29 at 12 17 45 PM" src="https://github.com/user-attachments/assets/58a17bc5-5ba6-42fb-8a1c-bb76f9babf28">   |
This is a final fix to the application table before shipping CDC 0157.
Try out CDC 0157's application table before and after.
=> Application list checkbox cells that are not sublists have bottom borders

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/nofos/templates/nofos/nofo_edit.html, bloom_nofos/nofos/utils.py
This PR does 2 things, but only 1 of them is important.
1. (Not important) Adding style maps for Word conversions
2. (Important) Adding a "copy links" button on the nofo_edit page
<details>
<summary>
Style maps explainer
</summary>
When we import .doc/docx files, we use [mammoth](https://github.com/mwilliamson/python-mammoth) to convert them to HTML first. It does a pretty good job, but sometimes it doesn't know what to do with specific formatting (you can see how text is formatted using the styles pane in Word). 
[Style maps](https://github.com/mwilliamson/python-mammoth?tab=readme-ov-file#styles) are explicit conversion rules that we can add. As an example: 
```
style_map_manager.add_style(
style_rule="p[style-name='Emphasis A'] => strong.emphasis",
location_in_nofo="Step 2 > Grants.gov …
```
=> Add button to copy list of broken links

CHANGELOG.md, bloom_nofos/bloom_nofos/static/shared.css, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/templates/nofos/nofo_index.html, bloom_nofos/nofos/test_nofo.py
1. Adds in a new background colour for table cells
2. Fixes CSS for the "Adam 👀" status (self-explanatory)
3. Fixes the asterisk problem we are seeing in table cells
This PR adds in a new background colour for tables so that we can have secondary header-like rows. 
| adding a new background colour |
|-------|
|    <img width="606" alt="Screenshot 2024-10-30 at 11 44 28 AM" src="https://github.com/user-attachments/assets/22dac2a0-6755-43d4-9219-8b4b5f787332">   |
| Adds the new light blue colour |
Sometimes we see asterisks cause text to be italicized inside of tables, when what we want is a literal asterisk. 
Here's an example.
| bad | good |
| italics are NOT intentional | literal asterisks showing up (*) |
| <img width="627" alt="Screenshot …
=> Light blue table rows + fix asterisks

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/templates/includes/form_macro.html, bloom_nofos/nofos/forms.py, bloom_nofos/nofos/mixins.py, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/templates/nofos/nofo_check_link_single.html, bloom_nofos/nofos/urls.py, bloom_nofos/nofos/views.py
This PR adds an external link checker for superadmin users. 
Sometimes when we use the external link checker, we see that some URL statuses fail even though it is possible to visit them in the browser. When this happens, it is generally not obvious what the issue is.
When I've investigated this in the past, I have been adding code manually to print the entire response and/or save to a file, which has worked but is not a good way to do things. This PR creates an actual page for us to do this in a nicer way, available only to superadmins. I don't expect we will need to use this very often but it is also pretty lightweight and will save me some time.
| page with successful URL | page with bad URL  |
|   Shows title, status code, and response if needed.     |   Shows the …
=> Admin external link checker

bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/test_nofo.py
This PR makes it so that when we see H7 headings come in (which we shim as `<div>` elements), that they are recognized as headings so that they create subsections as we expect.
Previously, these h7s were getting imported correctly, but they would just be part of the body of a section, they wouldn't actually be separated off as subsections like the other headings would.
=> H7s create subsections

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/bloom_nofos/templates/base_barebones.html, pyproject.toml
It used to be that we would just bold all table headings. But sometimes we have more complex table headings with several lines, typically the first line would be bold and then the ones after wouldn't be. 
Here's an example:
The update in this PR is to stop bolding paragraph tags inside of table headings. Mechanically, how the app works is that we leave the content of table headings in paragraph tags if there are hard returns in there. 
Here are some examples:
```html
<th>Heading 1</th> 
```
```html
<th>
<p>Heading 1:</p>  
<p>This is the first heading</p> 
</th>
```
```html
<th>
Heading 1:  
<p><strong>Important:</strong> This is the first heading</p> 
</th>
```
=> Stop bolding multi-line table headers by default

.github/workflows/google-cloudrun-docker.yml, CHANGELOG.md, Dockerfile, README.md, TODO.md, bloom_nofos/bloom_nofos/context_processors.py, bloom_nofos/bloom_nofos/settings.py, bloom_nofos/bloom_nofos/templates/base_barebones.html, pyproject.toml
Adding a GitHub Actions file to set up autodeployments to Cloud Run.
This PR works for most of the PRs we will have come through, but _does not_ work for migrations, which are still performed manually. 
This is good enough to merge though, as it will save us lots of time, and then I can reinvest some of that times to figure out this migrations step. 
Also bumping the version because this is a big step for the app.
=> Create GA autodeployment file

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/templates/includes/_text_input.html, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/templates/nofos/nofo_edit.html, bloom_nofos/nofos/templates/nofos/subsection_edit.html, bloom_nofos/nofos/test_nofo.py, bloom_nofos/nofos/utils.py, bloom_nofos/nofos/views.py
This PR makes two changes to the NOFO editing experience:
1. Show all heading levels in the nofo_edit page table.
2. List all H7s in the NOFO in an alert box
Because we don't have an automatic fix for shimming `<h7>` elements in the PDF itself, the solution has been to manually add H7 tags to the final PDF, which is a slow and annoying part of our process.
However, a challenge with this has been that the tag level of subheadings has not previously been surfaced to users of the NOFO Builder, leading to strategies like "look for all the h6s". This is clearly something fixable, so I've added a new column to the subsections table on the nofo_edit page which lists the heading level of each subsection (if the subsection has a title).
Now all heading levels can be viewed quickly.
| before | …
=> List H7s in an alert box + show all heading levels in edit_nofo page

CHANGELOG.md, bloom_nofos/nofos/nofo_markdown.py, bloom_nofos/nofos/tests/test_nofo_markdown.py
Sometimes we have tables that include content ending in asterisks that are meant to reference something at the bottom. 
In certain cases, the asterisks are interpreted as italics, not as the literal asterisk, which is what we want. 
[In a previous commit](https://github.com/HHS/simpler-grants-pdf-builder/commit/24449c4459b354a09627cab5705956fe26b2d772), I solved this for list items in table cells, but overlooked paragraphs.
This PR fixes that, so now — _I think_ — we are all set.
|  asterisks are being interpreted as markdown formatting, which is why some items are italicized (bad 👎)    | asterisks are preserved, as intended (good 👍) |
| <img width="715" alt="Screenshot 2024-11-13 at 3 41 56 PM" …
=> Convert literal asterisks into HTML entities in paragraphs in table cells.

CHANGELOG.md, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/test_nofo.py, bloom_nofos/nofos/utils.py, bloom_nofos/nofos/views.py
This one is strange. Most bookmarks are to headings, but sometimes they are to random areas in the middle of a paragraph.
When the document is exported as HTML from Word, the bookmark link _target_ is an `<a>` tag with with an id that matches the href (a normal anchor link).
However, once it goes through mammoth, it looks like they move the text out of the paragraph for some reason and then the (now-empty) link target gets stripped out of the text once the markdown conversion happens.
idk what is going on here, to be honest.
As an example, the Word HTML export will look like this.
```
<p>This is a paragraph link with <a id="my_id">a bookmark target</a>.</p>
```
But in the mammoth export, it looks like this:
```
<p>This is a paragraph link with <a id="my_id"></a> a bookmark target.</p>
``` …
=> Save some bookmarks 🙏

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-orientation-portrait.css, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/templatetags/add_classes_to_headings.py
Apparently some NOFO titles try to use the max character width they are allowed to, which is 250 characters. 
I find this puzzling, but as a non-NOFO expert, I try to keep an open mind about these things.
We already have a 'small' font variant, but this is an even smaller font variant.
Now the rule is:
- normal: 32pt
- over 120 chars: 28pt
- over 190 chars: 24 pt
Hopefully this fixes it, but we can tweak as we go.
|  28pt font for title      |  <sub>24 pt font for title</sub>       |
| <img width="1457" alt="Screenshot 2024-11-13 at 7 59 27 PM" src="https://github.com/user-attachments/assets/bf78dee5-a7ae-4f0f-b658-5d5edaa97a24"> | <img width="1457" alt="Screenshot 2024-11-13 at 7 59 32 PM" …
=> Smaller title font for larger titles

CHANGELOG.md, bloom_nofos/nofos/templatetags/add_classes_to_headings.py
I had assumed that titles move ~200 characters were the issue but we have seen then breaking at shorter lengths, so now we are saying 170.
This has been described already in #42, it's just we are lowering the character limit.
=> Smallen shorter titles (still long though)

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-orientation-portrait.css, bloom_nofos/nofos/templatetags/add_classes_to_headings.py
We made titles smaller in #42, but we have been seeing even longer titles sometimes. 
This PR adds another, even smaller font size for super long titles (> 230 chars).
This is hopefully the last time we have to do this.
| `24pt` font | `23pt` font |
|    <img width="879" alt="Screenshot 2024-11-18 at 1 59 27 PM" src="https://github.com/user-attachments/assets/897c71df-b551-455a-8796-aa745310cc74">    |  <img width="879" alt="Screenshot 2024-11-18 at 1 59 19 PM" src="https://github.com/user-attachments/assets/0a19f937-a009-42d3-8c4a-e9a81514e024">    |
=> Even smaller font sizes for NOFOs with titles over 230 characters long

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/bloom_nofos/static/theme-orientation-portrait.css, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/templatetags/add_classes_to_headings.py, bloom_nofos/nofos/templatetags/get_floating_callout_boxes_from_section.py, bloom_nofos/nofos/templatetags/utils/__init__.py, bloom_nofos/nofos/tests/test_templatetags.py
1. Makes the text in the right-col callout box smaller if it exceeds a certain word count
2. Adds some corrective CSS for multi-line table headings
3. Lowers the character limit needed for large titles to have a smaller font styling applied
We have been seeing these callout boxes split across 2 pages pretty regularly for the PEPFAR NOFOs. I've added a function that counts how many words are in the callout boxes and then applies styling based on that. Maybe a character count would be more exact, but let's try this for now.
| `10pt` font for callout boxes | `9.5pt` font for callout boxes |
|   <img width="861" alt="Screenshot 2024-11-20 at 10 35 51 AM" src="https://github.com/user-attachments/assets/36fd86ca-5edf-4c35-9197-107959 …
=> Smaller callout text + better table headings + smaller titles

.gitignore, CHANGELOG.md, bloom_nofos/nofos/management/commands/export_links.py, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/templates/admin/nofo_change_form.html, bloom_nofos/nofos/urls.py, bloom_nofos/nofos/views.py
1. adds a function to auto-replace known broken links on import
2. adds a script that we can use to grab all links across all NOFOs
3. removes an old view that would download a list of links from an individual NOFO
We noticed that some links 404 but still return a 200 level status code. This is very annoying. It is also not something we can do much about, as we only control one website.
However, we can find/replace stuff that we import, so if we know what URLs have this behaviour, we can resolve the problem when the file is imported. Right now there are 3 links we have identified:
| bad link | good link  |
|    [www.grants.gov/web/grants/search-grants.html](https://www.grants.gov/web/grants/search-grants.html)    | …
=> Replace broken links on import + add a script to download links

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/nofos/templates/nofos/nofo_view.html
This PR creates a "single-source" BYB page variant for NOFO CDC 0008.
In the future, this needs to be more general purpose, but for TODAY it will work.
|  <img width="831" alt="Screenshot 2024-11-22 at 4 38 59 PM" src="https://github.com/user-attachments/assets/a411af89-18c2-4f44-919e-878be49daa14">     |    <img width="831" alt="Screenshot 2024-11-22 at 4 37 38 PM" src="https://github.com/user-attachments/assets/684ced55-90ee-4cf5-bf35-c85773b50f65">  |
=> Create single-source Before You Begin page variant

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css
This PR includes 2 small CSS tweaks that make the NOFO look a bit nicer:
1. More space between multi-line anchors in the application checklist
2. Add a dash (`⁃`) character for quadruple nested bullets.
Previously, several multiline anchor tags in a row would just show up one after another with equal spaces between all lines, leading to an unclear separation between individual `<a>` elements. 
Make the line length a bit smaller and add some bottom margin to stacked anchors fixes this.
|   Unclear where line breaks are in second cell with 4 anchor lines     |  Line breaks are more evident       |
| <img width="691" alt="Screenshot 2024-11-27 at 3 49 13 PM" src="https://github.com/user-attachments/assets/ea434939-4758-4a00-8f3e-55a625d18ad3"> | <img …
=> CSS tweaks

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/nofos/templates/nofos/subsection_edit.html
This PR fixes a bug where the hit area was full-page width before, which meant that you could select "page break" without intending to do it.
Now it is the same length as the longest label, which will reduce unintentional clicks.
See below for a visual illustration of how much space was actually being given to the radio buttons/labels.
|  containing box is full-width, meaning you can easily select it unintentionally      |   containing box is only as long as the longest radio button label     |
| <img width="1557" alt="Screenshot 2024-12-02 at 12 33 39 PM" src="https://github.com/user-attachments/assets/ac5f5565-a75f-4230-b94f-0eca411cd9bf"> | <img width="1557" alt="Screenshot 2024-12-02 at 12 33 26 PM" …
=> Contain "Page break" hit area to just the radio button and label

CHANGELOG.md, bloom_nofos/bloom_nofos/context_processors.py, bloom_nofos/bloom_nofos/forms.py, bloom_nofos/bloom_nofos/settings.py, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/templates/base.html, bloom_nofos/bloom_nofos/templates/docraptor_live_mode.html, bloom_nofos/bloom_nofos/templates/includes/print_button.html, bloom_nofos/bloom_nofos/utils.py, bloom_nofos/bloom_nofos/views.py, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/templates/nofos/subsection_create.html, bloom_nofos/nofos/templates/nofos/subsection_edit.html, bloom_nofos/nofos/tests/test_utils.py, bloom_nofos/nofos/utils.py, bloom_nofos/nofos/views.py, bloom_nofos/users/managers.py, bloom_nofos/users/templates/users/login.html, bloom_nofos/users/templates/users/user_edit_password.html
This PR makes one major change, which is detailed in #83: Automatically flip back "LIVE" mode into "TEST" mode.
The idea here is that we have a limit on the number of "Live" NOFOs we can print, so we have invented this notion of "LIVE" and "TEST" modes. Usually you should be using "TEST" mode, since you can generate unlimited PDFs that way. When you need the good copy, change it to LIVE.  
However, not everyone changes it back, and since it is a global setting, we want to make sure that it doesn't stay on all day unintentionally.
This PR makes this change: it creates a 5 minute timer that is activated whenever you set the NOFO Builder to "LIVE". After 5 mins, it goes back to TEST mode. The idea is that you turn it Live, get your PDF, and then leave, and don't worry about it turning back. …
=> Automatically flip back "LIVE" mode into "TEST" mode

bloom_nofos/bloom_nofos/templates/400.html, bloom_nofos/bloom_nofos/templates/404.html, bloom_nofos/bloom_nofos/templates/500.html, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/views.py
Original issue: https://github.com/HHS/simpler-grants-pdf-builder/issues/25
This adds more specific error messaging for cases where validation errors are thrown for long headings. New text:
Screenshots: 
QA Steps:
1. Navigate to `http://localhost:8000/nofos/import`
2. Import a NOFO that has a heading that exceedes the character limit of 511
3. Verify that error message message renders as expected with a status code of 422
=> Heading length error messaging

CHANGELOG.md, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/test_nofo.py, bloom_nofos/nofos/views.py
This PR adds 2 things: 1 change and 1 bugfix.
1. Decompose "instructions" boxes for NEW NOFO WRITERS
2. `replace_chars` was not being applied — now it is
Content Guide documents have often have instructions for writers, explaining how to fill out the following section.
Previously, all of these boxes would be titled "Instructions for NOFO writers:", but now we are seeing a variant that goes "Instructions for new NOFO writers". Updated the function to remove these boxes as well.
|  layout is messed up. "Instructions for new NOFO writers" box should not be there.       |   Certified fresh.     |
| <img width="623" alt="Screenshot 2024-12-11 at 7 30 03 PM" src="https://github.com/user-attachments/assets/04c61bbb-7756-4c87-9c09-07a63507767b" /> | <img …
=> Fixes for new DGHP document

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/templates/includes/loading_horse.html, bloom_nofos/nofos/templates/nofos/nofo_import_overwrite.html
This is a small PR which is focused on the loading state when you are importing a NOFO.
1. Add the loading state to the re-import page
2. Make the button loading state more dynamic
This was pointed out to me earlier today as a bug. Since #71, when you are importing a NOFO, you see a little galloping horse, but on the _re-import_ page, nothing happens. 
This is now fixed.
Finally, the completion of my vision for the loading button on the import page. We now cycle through dots to indicate that it is working very hard on importing your NOFO.
This is a loading interaction for the ages.
=> Add loading gif to re-import screen + improve button loading state

CHANGELOG.md, bloom_nofos/nofos/management/commands/section_lengths.py
I don't know if we really need this for much but it's not really hurting anything.
Added a new Django command to pull down sections and subsections from non-archived NOFOs and to export them to a spreadsheet. 
It lives in the folder with our other commands. 
Run it with: 
```
poetry run python manage.py section_lengths --all
```
Or 
```
poetry run python manage.py section_lengths --nofo-id 1
```
=> Add script to find lengths of section.name and subsection.name values

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-opdiv-cms-blue.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cms.css
This PR Introduces various small improvements to the CMS "blue" theme. These are all things @admoorgit noticed when he was reviewing this theme:
- Fix background and text colour for cover page
- "Standard" icons are blue
- Tighter line-height for h5s
- Smaller, bolder h7s
The list of things to fix are in this doc: https://docs.google.com/document/d/1DlTUjmJL5XO8Y7rBfOMcXavl4gZWtiu0zNR7EkD7Egw/edit?tab=t.0#heading=h.vbol9hk2ixat
| before: cover page | after: cover page  |
|  cover page is messed up     |   cover page is good     |
| ![Screenshot 2024-12-18 at 5 52 37 PM](https://github.com/user-attachments/assets/95d27949-510e-4482-8b86-b1a496beb964) | ![Screenshot 2024-12-18 at 5 52 49 PM](https://github.com/user-attachments/assets/2d907688-6b2d-46be-b543-647c0eb0bf24) …
=> Updates to CMS blue theme

CHANGELOG.md, Dockerfile, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/test_nofo.py
This PR does two things:
1. Solves the import problem where NOFOs with h1s and h7s would fail to import
2. Doubles the app timeout time
Sometimes, we demote heading levels vs other times we don't.
When someone submits documents that have H1s in it, then we demote them all because there is only 1 H1 allowed in the document, for accessibility reasons.
Historically, this has meant that we have been demoting H6 levels to H7s, which is why we shim H7s.
However, when people submit a document that has H1s _and_ H7s, then it threw an exception and wouldn't import because there's no such thing as an H8.
This commit solves this by keeping the H7s as H7s, it doesn't demote them but it also doesn't cause an error when they show up.
We have had trouble importing long NOFO documents in prod because the …
=> Solve H7 bug when importing NOFOs + extend timeout time

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css
Sometimes we need different list counters for complex NOFO documents.
This PR adds some classes we can use to change the list counters to be roman numerals (i, ii, iii), uppercase roman numerals (I, II, III), alphabets, (a, b, c), and uppercase alphabets (A, B, C). 
We can't represent these in markdown, but we can convert to HTML and add the classes. 
```markdown
- one 
- two
- three
```
```html
<ol class="list-upper-alpha">
<li>one</li>
<li>two</li>
<li>three</li>
</ol>
```
```html
<ol class="list-lower-roman">
<li>one</li>
<li>two</li>
<li>three</li>
</ol>
```
=> Add utility classes for list counters

bloom_nofos/bloom_nofos/static/shared.css, bloom_nofos/bloom_nofos/static/theme-base.css
This PR is a follow-up from #132.
The last PR would add the list styling to the HTML view, but not to the edit view. 
This one brings that styling to the edit view as well.
=> Move utility classes so that they will show up in the edit view

CHANGELOG.md, Dockerfile, bloom_nofos/bloom_nofos/urls.py, bloom_nofos/nofos/api/api.py, bloom_nofos/nofos/api/schemas.py, bloom_nofos/nofos/api/tests.py, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/views.py, pyproject.toml
As we have continued to add steps to the NOFO import step, we've ended up increasing the total time needed to import a NOFO.
After running some profiling of the entire import step, we discovered the largest contributor to the import slowdown is the `add_headings_to_nofo` function, which was acocunting for over 60% of the import time for a typical NOFO.
Using a CMS NOFO as an example, we were seeing this online:
- Total import time: 21.829363 seconds 
- `add_headings_to_nofo` runtime: 14.137533 seconds
So if we can make this function more efficient, we can dramatically improve our NOFO import times.
=> Speed up NOFO importing

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/bloom_nofos/static/theme-orientation-portrait.css, bloom_nofos/nofos/templates/nofos/nofo_view.html
This PR makes 2 changes:
1. Adds new bullet styling for uls nested 5 and 6 times
1.1. Also fixes the 4th level nested bullets that use dashes
2. Makes all tables in appendices full-width 
|  orange: 4th level "dash" (-) bullets are nested incorrectly, pushing the first line in <br> purple:  5th and 6th level bullets are both using dashes (-)       |  orange: 4th level "dash" (-) bullets are nested correctly, so the entire block of text in `li` has the same left alignment  <br> purple: added black circles for 5th level bullets and outline circles for 6th level bullets     |
|   <img width="633" alt="Screenshot 2024-12-30 at 11 24 18 AM" src="https://github.com/user-attachments/assets/d56f6922-825f-4569-a30a-cf0733d39810" />     |    <img width="633" …
=> New ul bullets + wide tables in appendices

CHANGELOG.md, bloom_nofos/nofos/models.py, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/tests/test_utils.py, bloom_nofos/nofos/utils.py
This PR speeds up NOFO importing (again) by using batch processing inside of the `_build_nofo` function, which we use when creating a NOFO.
On Friday December 20th, we received the largest NOFO we had ever seen, and trying to import it actually would result in an app timeout on the server. 
So we started profiling the various functions we run in `import_nofo`, and discovered that we had a couple of noticeable bottlenecks:
1. `add_headings_to_nofo`: took `102 seconds` out of `129  sections` 
2. `create_nofo`: took `20 seconds` out of `129 seconds`
In PR #134, we refactored `add_headings_to_nofo` in 2 ways:
1. Move regex compilation out of the for loop: this accounted for the bulk of our time savings
2. Use batch updates to update all Sections and Subsections at once instead of calling …
=> Batch create Sections and Subsections in _build_nofo function

CHANGELOG.md, bloom_nofos/nofos/templatetags/replace_unicode_with_icon.py
This PR includes 1 change that accommodate a new set of tables we are seeing that use a sublist heading for the top 3 items.
The change in this PR is to add a sublist to the first few items in the application checklist table that starts with Narratives.
Specifically:
- headings with links must also not have a checkbox
- cells with "Narratives" are headings now
Tested with 12 other application checklists and it seems this is an acceptable change.
|  "Narratives" not identified as a heading. <br> Following rows can't be grouped together because they are links.      |   "Narratives" IS identified as a heading. <br> Following rows CAN be grouped together because they have checkboxes.    |
|   <img width="717" alt="Screenshot 2025-01-02 at 3 01 45 PM" …
=> Change how sublist headings are identified in application checklist

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/bloom_nofos/static/theme-opdiv-acf.css
issue: https://github.com/HHS/simpler-grants-pdf-builder/issues/130
Modifies headers to match new spec. h1, h4, and h7 are modified for the ACF theme
BEFORE:
AFTER:
=> acf heading style updates

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/nofos/templates/nofos/nofo_edit.html
This PR makes 3 changes:
1. Add h7 styles to the "edit" mode and "preview" pane in the markdown editor
2. Update body-text header styling in the NOFO content for the edit page
3. Remove the "Fix in Word and reimport" in heading error messages
Since our H7 styles are shimmed, they don't show up as regular HTML elements would. These means we need to add custom styling if we want to see them show up in the edit mode. 
Here is how it looks now in the "Edit" screen:
|  h6 is too small. <br> h7 has no styling.       |    h6 is proportional. <br> h7 is styled like a heading.  |
|      <img width="802" alt="Screenshot 2025-01-06 at 3 30 43 PM" src="https://github.com/user-attachments/assets/89e1630a-ca22-4094-b819-7f5fa1e88d49" /> |    <img width="802" …
=> Show H7 headings in "edit" and "preview" modes

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-opdiv-acf-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-dop.css, bloom_nofos/bloom_nofos/static/theme-opdiv-hrsa-white.css, bloom_nofos/nofos/templatetags/callout_box_contents.py, bloom_nofos/nofos/templatetags/utils/__init__.py, bloom_nofos/nofos/tests/test_templatetags.py
There are 3 (small) changes in this PR:
- Fixes links in callout boxes that touch the colon (solves issue #148)
- Standardizes our links as blue (Solves issue #147)
- Adds Jana as a designer (may remove this from the PR depending on whether #138 will go in afterwards)
This was to do with how HTML handles whitespace. When we had text only, the HTML looked like this:
```html
<p><strong>Stat authority:</strong><span> Here it is</span></p>
```
In that case, the space in the `span` element is preserved when rendered.
However, when the text after the colon started with a link, we would get this:
```html
<p><strong>Stat authority:</strong><span> <a href="https://google.com">Here it is</a></span></p>
```
This space disappears, and if we were to add a space to the link itself, we would see the …
=> Fix links in callout boxes + All links are blue

CHANGELOG.md, bloom_nofos/nofos/models.py
This PR contains 1 change, which is (in practice) to show the "Basic information" heading if our sections are out of order.
Not having this ordering logic was causing a subtle bug for us. If the first section _created_ was not Step 1, it would grab the first heading of the first section _created_, not "Step 1", which is what we would obviously prefer.
|    No "basic information" heading    |    All good!   |
|    <img width="583" alt="Screenshot 2025-01-13 at 6 20 22 PM" src="https://github.com/user-attachments/assets/032b6353-12f6-4ce9-96e5-b95e47299807" />  |   <img width="583" alt="Screenshot 2025-01-13 at 6 20 40 PM" src="https://github.com/user-attachments/assets/06cca957-48a1-4488-a736-a95281a867e4" />     |
This bug is described further in this …
=> Return sections by "order" for nofo.get_first_subsection()

bloom_nofos/nofos/api/api.py, bloom_nofos/nofos/api/tests.py
Issue: https://github.com/HHS/simpler-grants-pdf-builder/issues/159
This specifically addresses the second task in the above ticket.  This change makes it so that the api response has its sections and subsections are correctly ordered by their "order" property
Includes unit test
QA Steps:
- create a nofo
- add sections
- manually swap some sections around so that a they are in a different order than their creation order
- use the http://localhost:8000/api/nofos/{id} endpoint to retrieve that nofo
- verify that they are correctly ordered by order, not creation date
=> logic and tests for returning nofos with ordered sections

bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/templates/base.html, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/templates/nofos/subsection_edit.html
This is a small PR that adds some links to make the editing and reviewing process easier. 
- Add 'admin' links to the header in the edit pages
- Add 'Edit' link to the subsection edit page
- Fix a CSS problem with table headings in the markdown preview
Here's the biggest change as a screenshot.
|  Move "Admin" link to header      |   Add "View HTML" link in subsection    |
|     <img width="1566" alt="Screenshot 2025-01-17 at 5 44 00 PM" src="https://github.com/user-attachments/assets/a89c97a4-1e04-4cfa-bdf6-8ff0085cfb36" />   |    <img width="1566" alt="Screenshot 2025-01-17 at 5 43 27 PM" src="https://github.com/user-attachments/assets/f3efc1f4-8876-4db4-b713-c1b2cbf238a4" />   |
=> Add link to HTML from the subsection itself

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/templatetags/convert_paragraphs_to_hrs.py, bloom_nofos/nofos/templatetags/utils/__init__.py, bloom_nofos/nofos/tests/test_templatetags.py
This is an omnibus PR that solves all the `page-break` issues:
1. Allows `page-break` as a page-break string
2. Removes `-before` and `-after` strings from UI
3. Adds the `[ ↓ page-break ↓ ]` label to the edit page and the HTML view for subsection breaks
4. Solves the bug where page breaks don't get applied if there are no headings
All of these changes are backwards compatible, so nothing will change for existing NOFOs.
On the "edit" view
|  - (orange) top border is not labelled</br> - (green) 'page-break' is not recognized as a page break        |    - (orange) top border IS labelled now</br> - (green) 'page-break' IS recognized as a page break now       |
|    <img width="985" alt="Screenshot 2025-01-20 at 11 32 36 AM" …
=> Fix bage break UI & page break bug

CHANGELOG.md, TODO.md, bloom_nofos/bloom_nofos/templates/includes/_icon_macro.html, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/templatetags/get_breadcrumb.py, bloom_nofos/nofos/templatetags/utils/__init__.py, bloom_nofos/nofos/tests/test_templatetags.py
This PR makes a 2 changes:
1. Dynamically generate the top breadcrumb nav
2. Add the little lightbulb symbol icon for "Understand Review, Selection, and Award"
|   - hardcoded breadcrumbs, don't correspond with this NOFO (`3. Prepare` is wrong)<br/> - 🔍  Magnifying glass is the wrong icon   |  - dynamic breadcrumbs based on this NOFO (`3. Understand` is right)</br> - 💡 Lightbulb is the right icon     |
|     <img width="894" alt="Screenshot 2025-01-20 at 2 31 04 PM" src="https://github.com/user-attachments/assets/863f3cde-f118-41c4-be0a-5841ba834639" />   |    <img width="894" alt="Screenshot 2025-01-20 at 2 31 23 PM" src="https://github.com/user-attachments/assets/f7d1e05c-c68a-4918-bf2f-a895c9dde411" />   |
(2) is very simple, but I can expand a bit …
=> Dynamic breadcrumbs in top nav

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/nofos/templatetags/utils/__init__.py, bloom_nofos/nofos/tests/test_templatetags.py
This PR removes some classes to do with page breaks that weren't getting used.
I used to have these classnames:
- `page-break-before--container`
- `page-break-after--container`
- `column-break-before--container`
- `column-break-after--container`
But they weren't getting used, so we don't need them.
=> Remove nonessential page-break container classes

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/templatetags/add_classes_to_toc.py
This PR adds classes to the ToC section based on how many items are in the table of contents.
The reason for this change is that when the table of contents has too many items, sometimes one item drops onto the next page.
This PR tries to get ahead of that by shrinking the spacing between `<li>` elements if there are too many items in the table of contents.
I did a bunch of testing to arrive where I did, but still don't have a strong sense if this is the right cutoff / CSS to use. We will see in regular use if this works out or needs to be tweaked.
| ToC with 20 items | ToC with 27 items  |
|  Has classes: <br>-`toc--normal`<br>-`toc--items--20`       |     Has classes: <br>-`toc--small`<br>-`toc--items--27`   |
|   <img width="1254" alt="Screenshot 2025-01-22 at 4 33 …
=> Add classes to Table of Contents based on number of items

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/templates/nofos/nofo_import_overwrite.html, bloom_nofos/nofos/tests/test_reimport.py, bloom_nofos/nofos/views.py
This code allows us to save metadata for subsections on reimport, and apply them to the new import.  It tracks those changes and tells the user what changes were preserved as part of the success message on reimport.
QA Steps:
- Import a nofo
- make a subsection a callout field
- change a subsections html class
- reimport the same nofo
- verify that the success message reflects the changes you made
- verify that the changes are actually still what you set them to be
Note: There is currently behavior for page breaks that is showing them as changed, whether they were in the original document or not.  I'm not sure if this is actually an issue or not, to verify this, upload a nofo, and then reupload the same nofo.  The success message will tell you the page breaks are preserved, even if they …
=> Copy metadata for subsections on re-import of nofo

bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/views.py
This is a refactoring PR that doesn't change any logic or functionality but hopefully makes the codebase more composable (particularly soon).
There's not too much to point to here: basically, there is a big block of code that contains various small-ish-in-scope functions that process the initial NOFO on import. I have a similar function for the `suggest_*` funcs that used to be also all over NOFO import: https://github.com/HHS/simpler-grants-pdf-builder/blob/main/bloom_nofos/nofos/nofo.py#L1153
So this is the same thing really. The methods inside are all tested individually, so I haven't added tests for this aggregate function.
The other thing I want to call out is that I created a debug HTML output file whenever we are running in DEBUG mode. I turn this on and off selectively as it is …
=> Refactor nofo_import: Move 'process the HTML' steps into their own function

bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/views.py
This is a hotfix PR that fixes an issue to do with importing NOFOs. The short version is, we weren't actually returning the "soup" after processing it, so the imported NOFOs were full of layout problems.
=> Fix NOFO HTML processing step

bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/tests/test_reimport.py, bloom_nofos/nofos/urls.py, bloom_nofos/nofos/views.py
This PR breaks up our `nofo_import` function into 2 class-based views: 
1. NofosImportNewView: for importing a new NOFO
2. NofosImportOverwriteView: for overwriting an existing NOFO
Logic and functionality are unchanged from before, this is strictly a refactor so that sets us up for some of the 'reimport' stories we have in the pipeline (#125, #156, #170).
The diff is not very helpful in this PR. I would suggest just reading through the final `views.py` to understand what's happening.
It is the final PR in the "Refactor nofo_import" series, which included these other ones:
- #191 
- #192 
For a long time, we were using a function-based view called `nofo_import` which handled both importing a new NOFO and overwriting an existing NOFO. This made sense because there is a bunch of shared …
=> Refactor nofo_import: Create "NofosImportNewView" and "NofosImportOverwriteView"

CHANGELOG.md, bloom_nofos/nofos/templates/nofos/nofo_confirm_delete.html, bloom_nofos/nofos/templates/nofos/nofo_import_confirm_overwrite.html, bloom_nofos/nofos/templates/nofos/nofo_import_overwrite.html, bloom_nofos/nofos/tests/test_models.py, bloom_nofos/nofos/tests/test_reimport.py, bloom_nofos/nofos/urls.py, bloom_nofos/nofos/views.py
This PR does 1 major thing and 1 minor thing:
1. Add a confirmation page when re-importing a NOFO with a different ID
2. Suppress the "DELETE" warning in our test suite
This is based on a post-mortem we had a couple of weeks ago. Basically, someone re-imported a NOFO document _for a different NOFO_ and then wiped out a bunch of content. 
In the event, we were able to restore from a backup, but it signalled to us that we should take some action around this.
This PR introduces a new view (`NofosConfirmReimportView`) which shows up when you upload a document to re-import but the document is found to have a different NOFO opportunity number, which suggests you may have the wrong document. At this point, you still _can_ reimport if you want, or you can back out of it and return to the original …
=> Add "Are you sure?" confirmation page when re-importing a NOFO with a different ID

bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/test_nofo.py
issue: https://github.com/HHS/simpler-grants-pdf-builder/issues/203
Changes:
- defines is_h7 at the module level so it can be reused
- reworks tag handling in preserve_heading_links method to account for h7s
- The actual changes here are really just 2027-2037, the rest of LoC is just nesting changing
- Adds unit tests for h7 link preservation
QA Steps:
- Import a nofo with h7 headings (like CDC-00009)
- Verify there are no broken links
=> Add h7 processing to link preservation

.gitignore, CHANGELOG.md
This is a very small PR that is all about DX.
Basically, since the Login.gov PR (#200) is up, I have had this `bloom_nofos/bloom_nofos/certs` directory in my app and it is constantly getting flagged by git as a new file on all other branches. Very annoying!
We can't exactly merge in the login.gov stuff yet, but we _can_ merge in this change to the `.gitignore` file and it will make switching branches seamless.
=> Ignore login.gov directories and files

CHANGELOG.md, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/test_nofo.py, bloom_nofos/nofos/views.py
This PR adds a new subsection to the end of step 3 with the following text:
```
Important: public information
When filling out your SF-424 form, pay attention to Box 15: Descriptive Title of Applicant's Project.
We share what you put there with [USAspending](https://www.usaspending.gov/). This is where the public goes to learn how the federal government spends their money.
Instead of just a title, insert a short description of your project and what it will do.
```
This will be added to the end of any section named "Step 3: Prepare Your Application" or Step 3: Write Your Application".
Once this goes in, it will be added to every uploaded NOFO from now on. This is what we want, right, @admoorgit?
| editing view | html view  |
|  this new section in the editing view …
=> Add new subsection "Important: public information" at the end of step 3

CHANGELOG.md, bloom_nofos/nofos/migrations/0090_add_public_information_subsection.py, pyproject.toml
Mimics the logic in add_final_subsection_to_step_3 but for a migration to add the PUBLIC_INFORMATION_SUBSECTION to existing NOFOs.
=> Migration to add public info subsection to existing NOFOs

bloom_nofos/nofos/partials/audit_events_rows.html, bloom_nofos/nofos/templates/nofos/nofo_edit.html, bloom_nofos/nofos/templates/nofos/nofo_history.html, bloom_nofos/nofos/templates/nofos/nofo_index.html, bloom_nofos/nofos/tests/test_history.py, bloom_nofos/nofos/urls.py, bloom_nofos/nofos/views.py
Issue: https://github.com/HHS/simpler-grants-pdf-builder/issues/171
Changes:
- Adds button to edit page linking to audit page
- Adds Audit page at /nofo/{id}/history
- Adds unit tests audit page logic
- Adds link from index page on updated timestamp
screenshots:
=> audit page added with tests and infinite scroll

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css
This PR makes two changes to our final NOFO Builder PDF output:
- No longer have clickable top-nav breadcrumb links
- When opening in Acrobat, the Bookmarks tab will be open by default
The top-nav links being clickable was super annoying for screen readers, as they would be constantly reading all those links on every single page of the NOFOs, and there was no way to prevent this.
In the end, we decided that the best way forward is to leave the links in there so that they signpost where the user is in the NOFO (eg, it will indicate they are in section 3, for example), but to nullify them so they are no longer clickable.
To offset this, we also always want the Bookmarks tab to be open in Adobe, so that the structure of the NOFO is visible and navigable using in-app tools.
=> Nullify clickable "top-nav" breadcrumb links on every page

bloom_nofos/nofos/views.py
Adds a fallback for cases where there is no section or subsection data for whatever reason.  This should at least avoid our 500 error. Also convert the obeject_id to a string before making the query (https://github.com/soynatan/django-easy-audit/blob/d2941373dd2107bc7994884cb044fcd2af2bb086/easyaudit/models.py#L35)
=> Adds fallback to section and subsection queries

bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/nofos/templates/nofos/nofo_edit.html, bloom_nofos/nofos/templates/nofos/nofo_history.html, bloom_nofos/nofos/templates/nofos/nofo_index.html, bloom_nofos/nofos/views.py
Changes are as follows:
Nofo index page:
- change timestamp on index page to not use military time
Nofo edit page:
- remove "Audit history button": too noisy
- add a "last updated" widget and a right-justified link to audit history
Nofo audit page:
- call them "Updates" instead of audits
- move the little "group" badge a little lower (too tight before)
- timestamp cell is more roomy
- more distinction between the "event" object type and the actual changed object
- only print email of user, not name
- change timestamp to always include time, format it in a 12h format
=> Clean up some of the Audit history UI (very small PR)

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/templates/includes/feedback_link.html, bloom_nofos/nofos/models.py, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/templates/nofos/nofo_compare.html, bloom_nofos/nofos/templates/nofos/nofo_import_compare.html, bloom_nofos/nofos/templates/nofos/nofo_import_overwrite.html, bloom_nofos/nofos/tests/test_compare.py, bloom_nofos/nofos/tests/test_models.py, bloom_nofos/nofos/urls.py, bloom_nofos/nofos/views.py
- This is related to https://github.com/HHS/simpler-grants-pdf-builder/issues/125,
- It's also the continuation of #144, which has been closed.
The idea here is a UI concept for comparing a NOFO to another NOFO document. (The more expansive concept is to add a step like this on re-import, but I think that "compare" is a big enough feature on its own and something that we can ship and get feedback on before we make this part of the re-import flow.) 
The objective is to provide a simple way for people to identify changes that have happened since their last import, so they can see what the damage would be if they re-imported and overwrote what they currently have.
Only the NOOF attributes and subsections that have changed are shown on the comparison page. This means attributes/subsections …
=> Compare NOFOs including text diff

CHANGELOG.md, bloom_nofos/bloom_nofos/templates/includes/feedback_link.html
Very simple PR that swaps our feedback form from a Google Form to an MS365 form. 
Often, government users are blocked from using G-Suite products, so this is hedging against that outcome.
Old form: https://docs.google.com/forms/d/e/1FAIpQLSdck-FeYXnp-LwsvD4lsdr7dfPOKbBb2ZW2hcoPZpWDYVtsRQ/viewform
New form: https://forms.office.com/Pages/ResponsePage.aspx?id=ZQrp8hdH80WEeW57vbgMkchDgIu0IAJAnHQJqY67rEdUMzg1RURBV1hUR1FKQklHTloyMkJDNU05MC4u
=> Swap the feedback form to use a Microsoft 365 form

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/templates/includes/feedback_link.html, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/templates/nofos/nofo_compare.html, bloom_nofos/nofos/tests/test_compare.py
This PR makes a bunch of changes to the diff interface. If you thought it was good before, prepare to be WOW'd!!
1. Use full-word diffs
2. Show linebreaks that exist in body content (easier for lists, for example)
3. Reclassify whitespace-only changes as "MATCH" not "UPDATE" (in markdown, they generally don't matter)
4. Hide the "Basic information" subsection because it duplicates information
Here is a big before/after screenshot (new screenshot is much shorter), but each of these is explained more before.
|     ![localhost_8000_nofos_405_compare (1)](https://github.com/user-attachments/assets/c45820ed-f0dc-4863-ac23-207439311a72)   |   ![localhost_8000_nofos_405_compare](https://github.com/user-attachments/assets/b491587e-b4cf-409c-81a8-dc51ff58680b) …
=> Improvements to the diff interface

CHANGELOG.md, bloom_nofos/nofos/models.py, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/test_nofo.py, bloom_nofos/nofos/tests/test_models.py, bloom_nofos/nofos/views.py
This PR adds logic to the function that inserts a new subsection inside of "Step 3": https://github.com/HHS/simpler-grants-pdf-builder/pull/96
In particular, we add logic so that the new subsection can be inserted after specific headings, not just at the very end of Section 3. 
The headings we are looking for are:
- Other required forms
- Standard forms
- Application components
If multiple of these exist, the new subsection will be inserted after the first one we find. If none of them exist, the new subsection would be inserted at the end of section 3 (which is the current behaviour).
| "Other required forms": before | "Other required forms": after |
|   <img width="787" alt="Screenshot 2025-02-26 at 4 13 14 PM" …
=> Add "Important" subsection after specific headings in step 3

CHANGELOG.md, bloom_nofos/bloom_nofos/static/shared.css, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/bloom_nofos/templates/base_barebones.html
This commit does 2 things:
- does not apply standard list types to `<ol>` and `<ul>` elements with "type" attributes
- also make sure that our `<ol>` and `<ul>` styling is applied to all views, the html view, the edit view, and the "preview" view.
Here's a before and after. It's a bit hard to see, but you gotta trust me:
|  `ol` should be: `A`, `1`, `a`, `I`, `a` <br> `ol` is: `A`, `a`, `i`, `i`, `i` <br><br> `ul` should be all squares<br> `ul` is not all squares   |    `ol` should be: `A`, `1`, `a`, `I`, `a` <br>   `ul` is all squares |
|     <img width="676" alt="Screenshot 2025-03-04 at 12 20 47 PM" src="https://github.com/user-attachments/assets/31c45d4a-27f0-46a8-a946-0b76b30c1272" />   |    <img width="676" alt="Screenshot 2025-03-04 at 12 19 …
=> Do not apply default list-types to list elements with "type" attr

bloom_nofos/bloom_nofos/static/shared.css, bloom_nofos/bloom_nofos/templates/base_barebones.html
In my exuberance to fix the list problems in #228, I accidentally caused 2 issues:
1. Table of contents lists would have small roman characters as markers ("a", "b", "c", etc) 
2. Section page header listings were invisible in the CDC theme (this was due to CSS cascading, not lists per sé)
This commit fixes both of these issues.
|   <img width="801" alt="Screenshot 2025-03-04 at 4 28 45 PM" src="https://github.com/user-attachments/assets/f1d2ea62-533d-4a53-8c4d-da54f6ad91cf" />     |    <img width="801" alt="Screenshot 2025-03-04 at 4 27 45 PM" src="https://github.com/user-attachments/assets/936ad0a6-2985-4ef7-9c60-c215cbf6744a" />   |
|    <img width="801" alt="Screenshot 2025-03-04 at 4 28 34 PM" …
=> [BUG] Fix the ToC lists and section page lists

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-dhp.css, bloom_nofos/nofos/templates/nofos/nofo_view.html, pyproject.toml
This PR is very small, and makes 2 changes:
1. Smaller callout text when 80 chars or more
2. Change colours of top nav items in DHP section pages
It also updates the version number in the `pyproject.toml` to match what is in our changelog.
The only visual change is to the top nav breadcrumb items on section pages in the DHP theme. They look less clown-y.
|    <img width="518" alt="Screenshot 2025-03-05 at 4 54 11 PM" src="https://github.com/user-attachments/assets/3bda42ee-5674-4f73-87f5-506f07a0627e" />    |   <img width="518" alt="Screenshot 2025-03-05 at 4 53 42 PM" src="https://github.com/user-attachments/assets/394db50c-3655-40fb-bb0a-b1093eb27b8d" />    |
=> Small PR that lowers word count for callout box CSS and updates nav colours for DHP theme

CHANGELOG.md, bloom_nofos/bloom_nofos/static/shared.css, bloom_nofos/nofos/templates/nofos/subsection_create.html, bloom_nofos/nofos/templates/nofos/subsection_edit.html
This is huge, we have added a new button colour.
Previously, I have stuck with the USWDS button colours but they can be a bit limiting, so now I have added this new one.
Used colours that are already part of USWDS.
(Look for ".usa-icon-list--success-dark .usa-icon-list__icon")
Added for these states:
- normal
- hover
- active
"disabled" already has CSS, so all good there.
| default button colour | lucky! 🍀 button colour |
|    <img width="187" alt="Screenshot 2025-03-07 at 3 10 21 PM" src="https://github.com/user-attachments/assets/86a07b2e-a5ab-43a0-a1ef-e19630f92bcb" />    |    <img width="187" alt="Screenshot 2025-03-07 at 3 10 01 PM" src="https://github.com/user-attachments/assets/7c377346-4e96-40c8-9ccf-0d53700533ab" />   |
=> Add green buttons for St. Patricks' Day 🍀 

CHANGELOG.md, bloom_nofos/nofos/nofo_markdown.py, bloom_nofos/nofos/tests/test_nofo_markdown.py, bloom_nofos/nofos/utils.py
This PR updates our style mapping to accommodate 2 new styles:
- those that start with "w:" 
- "heading 8"
Note that we don't support heading-8s, but we do want to be able to identify them when they happen, so I've kept them as divs with a classname rather than just a paragraph tag or something generic.
=> Update style map

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/NOFO.yml
For now, we are just testing these to see if they work.
Documentation is here:
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
=> Add 2 GitHub issue forms

CHANGELOG.md, bloom_nofos/nofos/templates/nofos/nofo_check_links.html
Very small PR. 
This was raised during our NOFO Builder retro, and it's easy so let's just do it.
|  429 not mentioned      |  429 _is_ mentioned      |
|   <img width="849" alt="Screenshot 2025-03-10 at 4 30 07 PM" src="https://github.com/user-attachments/assets/c363176e-94a0-4e4c-8a65-49db66d74a4a" />     |   <img width="849" alt="Screenshot 2025-03-10 at 4 29 19 PM" src="https://github.com/user-attachments/assets/b127517e-5134-42e6-97bc-043199badc54" />    |
Once this is merged, #226 is closed!
=> Explain `429` status codes in the external links status table

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css
This is a small PR that fixes a visual bug we have only in the Safari browser.
In the nofo_edit view, the "page-break" `::before` element was not contained by the `<tr>` element, and so would float up to the top of the browser window.
Added some hacky CSS to put it where we expect, although it won't work on a mobile screen.
| subsection page-break | floats to the top of the page |
|   <img width="1016" alt="Screenshot 2025-03-11 at 10 26 45 AM" src="https://github.com/user-attachments/assets/5570b0e8-d7cc-4dff-abdb-5336c653e92c" />     |    <img width="1016" alt="Screenshot 2025-03-11 at 10 26 28 AM" src="https://github.com/user-attachments/assets/947d6a66-bc58-4024-a367-8d15fb34bf06" />   |
=> [Bugfix] Fix Safari-specific page-break bug

bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/test_nofo.py, bloom_nofos/nofos/views.py
This PR fixes a bug (technically) where the step 2 links in the BYB page were hard coded. This meant that if there was a differently-named "Step 2", the links would break. 
NOW, we pull the Step 2 dynamically, and if we don't have one we show a big load highlighted error message that someone will notice before it goes to publish.
| before | after | no step 2
|--------|-------|-------|
|   before: hardcoded links     |  now: dynamic links     |  if no step 2: show warning message     |
|     <img width="715" alt="Screenshot 2025-03-11 at 11 52 40 AM" src="https://github.com/user-attachments/assets/240197e6-8d8d-48ad-96e8-8440246b75b5" />   |    <img width="715" alt="Screenshot 2025-03-11 at 11 53 15 AM" src="https://github.com/user-attachments/assets/9be5b890-c478-4e67-b791-758fe96a62c1" …
=> Fix Before you begin page so that "step 2" links are dynamic

CHANGELOG.md, bloom_nofos/bloom_nofos/static/shared.css, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-dhp.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-iod.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-orr.css, bloom_nofos/bloom_nofos/static/theme-orientation-portrait.css, bloom_nofos/bloom_nofos/utils.py, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/templates/nofos/nofo_view.html, bloom_nofos/nofos/test_nofo.py, bloom_nofos/nofos/tests/test_utils.py
This PR makes 4 changes so that we are ready for a demo later today.
1. Replace double newlines in alt text so that images render properly in markdown
2. Add rounded corners to inline images by default
3. Remove the "Jump to a step" line in section title pages
4. Extend timeout for "live mode" to 90 minutes
When you import an image into Word, you get auto-created alt text like this:
```
A turtle in a tank.
AI-generated content may be incorrect.
```
Because there are 2 newlines in there, it breaks our markdown rendering, so we replace `\n\n` in image alt texts with `\n`.
Also add styling so that inline images have rounded corners.
|     <img width="835" alt="Screenshot 2025-03-13 at 12 04 50 PM" …
=> Fix newlines in image alt text, remove "Jump to a step", extend "live mode" timeout

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/bloom_nofos/static/theme-opdiv-acf-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-acf.css, bloom_nofos/bloom_nofos/static/theme-opdiv-acl-white.css, bloom_nofos/bloom_nofos/static/theme-opdiv-acl.css, bloom_nofos/bloom_nofos/static/theme-opdiv-aspr.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-dhp.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-iod.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-ncipc1.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-ncipc2.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc-orr.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cdc.css, bloom_nofos/bloom_nofos/static/theme-opdiv-cms.css, bloom_nofos/bloom_nofos/static/theme-opdiv-hrsa.css, bloom_nofos/bloom_nofos/static/theme-opdiv-ihs.css, bloom_nofos/bloom_nofos/static/theme-orientation-landscape.css
This a very small PR that makes 2 styling updates:
- Make top border for breadcrumb links 5px
- Set the running header at 20mm height so they are flush against the top.
|   8mm gap in breadcrumb links     |  breadcrumb links are flush with the top of the page      |
|   <img width="1050" alt="Screenshot 2025-03-13 at 12 58 36 PM" src="https://github.com/user-attachments/assets/bdf7b066-1e63-4e4c-9959-afb6dadc28c3" />     |   <img width="1050" alt="Screenshot 2025-03-13 at 12 58 45 PM" src="https://github.com/user-attachments/assets/87278693-399f-4fe8-a5ad-3b5b651440b3" />    |
=> Breadcrumb links now have a 5px top-border

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css
We have some colour blocks at the top for broken links, heading errors, and h7s.
The h7s aren't really errors, but the other two are like: "hey, go fix this".
One of the feedback comments was that we should match the tooltip colours with the colour blocks that we use for the errors.
This isn't really a huge deal, but it's also an easy fix to make, so why not just do it?
|   <img width="211" alt="Screenshot 2025-03-15 at 5 24 00 PM" src="https://github.com/user-attachments/assets/61c5a634-3613-4310-a6b9-921f849ae042" />     |   <img width="211" alt="Screenshot 2025-03-15 at 5 23 16 PM" src="https://github.com/user-attachments/assets/ec1656c3-952f-49dd-88c3-0cb082561179" />    |
|   <img width="273" alt="Screenshot …
=> Match the error and tooltip colours in nofo_edit view

CHANGELOG.md, bloom_nofos/bloom_nofos/utils.py, bloom_nofos/nofos/tests/test_utils.py
This was extended in order to not revert during a demo but now the demo is over.
=> "Live mode" timeout is 5 minutes

CHANGELOG.md, bloom_nofos/nofos/templates/nofos/nofo_edit.html
This PR adds a tooltip to the callout box emoji that says "This subsection is a callout box".
Very simple. 
Here's a screenshot:
---
And here is the USWDS page that shows how tooltips work: https://designsystem.digital.gov/components/tooltip/
Merging this PR closes #225
=> Add a tooltip to the callout box emoji

bloom_nofos/nofos/nofo_markdown.py, bloom_nofos/nofos/tests/test_nofo_markdown.py
This PR adds default column width classes to HTML tables. This means we will have parity between markdown tables and HTML tables. 
The idea is, for tables with x columns, we add classes to make them equal width:
- 3 columns: `w-33`
- 4 columns: `w-25`
- 5 columns: `w-20`
Once your table is more than 6 columns, I am assuming it's too weird and I am not going to add presumptive classnames to your table.
Previous commit is here: https://github.com/HHS/simpler-grants-pdf-builder/commit/335d73829b7b5480608d0db72a7f8bb6663fc501
|   second table has uneven column widths     |  both tables look the same 👯      |
|    <img width="475" alt="Screenshot 2025-03-26 at 10 45 56 AM" src="https://github.com/user-attachments/assets/eac43d4d-3af1-4840-919b-7f0239b3a955" …
=> Add default column classes to HTML tables 

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/nofos/templates/nofos/subsection_create.html, bloom_nofos/nofos/tests/test_subsection_create.py, bloom_nofos/nofos/views.py
This PR shows the previous subsection (and heading level) on the "new subsection" page.
This came from a ticket that we got in our feedback sessions, which said:
> From the Add Subsection area, it would very helpful to have which Heading level it currently is, we have to toggle back and while we are focusing on other area’s i forget.
It is a smart point and not that complicated to build, so I built it. 
There is a slight complication, where if the previous subsection does not have a title, then we have to find the one before that (could loop forever), but in practice, this would almost always just be the previous to the previous one. So we always make sure to show the heading level.
| cannot tell what previous heading level was       |   show previous …
=> Show previous heading level on new subsection page

bloom_nofos/bloom_nofos/utils.py, bloom_nofos/nofos/tests/test_utils.py
Small PR that sets our "Live mode" timeout (back) to 5 mins. 
This reverts the change made in #271 
The presentation is over, so now back to normal.
=> Revert "Live mode" to 5 mins again

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/templates/base_barebones.html, bloom_nofos/nofos/templates/nofos/nofo_edit.html, bloom_nofos/nofos/templates/nofos/subsection_edit.html, bloom_nofos/nofos/tests/test_subsection_create.py, bloom_nofos/nofos/views.py, bloom_nofos/users/views.py
This PR is a small in terms of code, but larger in terms of modifying how editing works in the NOFO Builder. 
It changes the "Save" and "Back" actions when editing a subsection to load the NOFO edit page at the top of the current subsection, not at the top of the page. There are a couple of cards about this that showed up in the retro:
> After you edit and save a subsection, stay in the section area you're in, instead of directing you to the top of the document each time.
> I’d like to stay in the area of section I’m working on after I hit the ‘save’ button. Now it jumps to the top of the document.
Also, it does the same thing when you add a new subsection:
> I wish the “add subsection” button, when clicked, would land me in the same spot as where i clicked it (instead of me having to …
=> Scroll to the section you have just edited

CHANGELOG.md, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/test_nofo.py
Pretty small PR. This updates the function that changes body content when we click the "add modifications" button. 
Usually they say Announcement version: New, but sometimes they don't I guess.
Follow up from: #263
=> Also automatically convert "Annoucement version: initial"

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-base.css, bloom_nofos/nofos/templates/nofos/nofo_edit.html, bloom_nofos/nofos/templates/nofos/nofo_edit_modifications.html, bloom_nofos/nofos/templates/nofos/nofo_view.html
This is a small PR that changes the message on the front cover of the NOFO.
Previous: `Modified [date]. Review updates.`
New: `Last modified [date]. Review updates.`
It is slightly more explicit than before, I think.
|   <img width="331" alt="Screenshot 2025-04-03 at 11 04 31 AM" src="https://github.com/user-attachments/assets/d862e57a-789f-4905-9100-024c5c2811eb" />     |   <img width="331" alt="Screenshot 2025-04-03 at 11 04 09 AM" src="https://github.com/user-attachments/assets/e5229adf-f4c6-4f03-946d-3df596b8067e" />    |
=> Change cover page "modifications" message for HRSA NOFOs

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/nofos/audits.py, bloom_nofos/nofos/templates/nofos/nofo_edit.html, bloom_nofos/nofos/templates/nofos/nofo_history.html, bloom_nofos/nofos/templates/nofos/nofo_history_modifications.html, bloom_nofos/nofos/templates/nofos/subsection_create.html, bloom_nofos/nofos/templates/nofos/subsection_edit.html, bloom_nofos/nofos/tests/test_audits.py, bloom_nofos/nofos/tests/test_subsection_edit.py, bloom_nofos/nofos/urls.py, bloom_nofos/nofos/views.py
This PR is pretty large. It adds:
- a new page for audit events since "add modifications" button was clicked
- shows the markdown table code you can use to update your modifications table subsection 
- a link to this new page from other audit events page
- a link to this new page from the "other actions" box on nofo_edit page
- shows the "last modified" date in the "other actions" box and adds a link to change it on the nofo_edit page
- shows the "last modified" date and a link to change it on the subsection edit page for the modifications table
The idea here is that people who are modifying NOFOs are making a large number of small edits across many subsections, and trying to remember them all manually is really annoying and impractical. This makes that process easier, using information …
=> Show audit events since modifications

CHANGELOG.md, bloom_nofos/nofos/nofo_markdown.py, bloom_nofos/nofos/tests/test_nofo_markdown.py
Starting since [I last updated markdownify](https://github.com/HHS/simpler-grants-pdf-builder/pull/267), we have seen problems with our nested lists being interpreted correctly in markdown.
The issue appears to be that instead of using tabs as the indentation for nested lists, the new update has been using  2 or 3 spaces, depending on whether the list was a UL or an OL.
So for this UL as HTML:
```
<ul>
<li>
Unordered list level 1
<ul>
<li>
Unordered list level 2
<ul>
<li>
Unordered list level 3
<ul>
<li>Unordered list level 4</li>
</ul>
</li>
<li>Unordered list level 3</li>
</ul>
</li>
<li>Unordered list level 2</li>
</ul>
</li>
<li>Unordered list level 1</li>
</ul>
```
this is what we would get as the markdown string:
```
* Unordered list level 1
+ Unordered list level 2
- Unordered list …
```
=> Fix for insufficient nested lists markdown indentation

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/guides/templates/guides/guide_edit.html
This PR builds the "edit" page for a content guide. 
This is the page where we will configure the subsections of a content guide, as well as change the name or do comparisons or whatever else we want, really. It's not really functional yet, as we still have to add the subsection edit page as well as update the compare function to work with non-Nofo objects, but that's all good.
At least this gives us something to work with. 😄 
|   basic page where you could only edit the title     |  more normal looking page where you can see all your subsections      |
|     <img width="1193" alt="Screenshot 2025-04-11 at 12 05 08 PM" src="https://github.com/user-attachments/assets/c3923792-79e8-4ca4-8b86-76e5b119ab86" />   |   <img width="1193" alt="Screenshot …
=> Add Content Guide "edit" html template

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css
This is a relatively small PR but hopefully one that has a big impact. 
This PR is aimed at helping NOFO designers when they apply table widths. The problem to be solved here is that writers/designers adding table widths didn't know if they were being applied correctly.
Given that, there are 3 changes in this PR regarding table widths:
1. Actually implement the widths in the nofo_edit page
- Previously, applied widths would have no effect on the nofo_edit layout
2. Show the classnames on the nofo_edit page, in the th elements
3. Show the classnames in the martor preview, in the th elements
|  equal-width columns. no indication that widths had been explicitly applied.      |  columns are 25%, 25%, 50%. width classnames have been added to the `th` …
=> Show table widths explicitly on "nofo_edit" page

bloom_nofos/guides/templates/guides/guide_compare.html, bloom_nofos/guides/views.py, bloom_nofos/nofos/nofo_compare.py, bloom_nofos/nofos/templates/nofos/nofo_compare.html, bloom_nofos/nofos/tests_nofos/test_compare.py, bloom_nofos/nofos/views.py
This PR improves how we handle which values to display on the `*_compare` pages. 
Previously, we added code to the template and/or the view itself that would remove, say, all `MATCH` results from the array of diffs. Since this was being done in 2 places, we were duplicating code in some places and adding inconsistencies in others. 
This has now been rewritten so that we have a much greater control over which subsections we want to show. By default we will exclude all `MATCH` results from all comparisons, but I think we will expand this in the near future to remove all `ADD` results when we are comparing a content guide to a NOFO (we expect there to be additions, we don't care about those).
No screenshots here because the logic has been moved but there is no user-visible change.
=> Filter compare dict items by status before displaying them

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/guides/views.py
This is a small change to the content guide comparison screen.
- Don't show `ADD`ed subsections: when comparing against a Content Guide, we expect there to be lots of ADDs, what we care about is what has changed or been removed.
- Don't show the red strikethrough effect on deleted text: they decrease readability.
|  - red strikethrough on deleted text <br>- ADD subsection    |  - no read strikethrough<br>- No more ADD     |
|   <img width="820" alt="Screenshot 2025-04-23 at 9 24 53 AM" src="https://github.com/user-attachments/assets/fbedf032-b082-431a-8099-d1677546fae8" />     |     <img width="820" alt="Screenshot 2025-04-23 at 9 28 41 AM" src="https://github.com/user-attachments/assets/1020db0e-a82b-46ca-acdc-211c719a6cd7" />  |
=> Hide ADDs and red lines on the content guide compare page

bloom_nofos/nofos/nofo_compare.py, bloom_nofos/nofos/tests_nofos/test_compare.py
This PR does not change any logic or user-visible behaviour, instead it is an internal refactor to keep our codebase maintainable.
Previously, we were using `dicts` for our subsection comparisons, which have the benefit of being flexible (easier to build, easier to work with), but have the drawback of being unstructured (anything can be assinged to any key, new keys can be created on the fly, no guarantee of anything).
Now that we have a strong opinion about what subsection diffs should look like, it was time to introduce more of a strict data type around subsections, so voila.
This refactor sets us up for a more maintainable diff feature.
=> Compare refactor: introduce `SubsectionDiff`

CHANGELOG.md, bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/nofos/nofo.py, bloom_nofos/nofos/nofo_compare.py, bloom_nofos/nofos/templates/nofos/nofo_edit_application_deadline.html, bloom_nofos/nofos/test_nofo.py, bloom_nofos/nofos/views.py
This PR modifies the "Change Application Deadline" view by showing all other subsections where the current application deadline exists and offering to change them all at the same time.
This story came out of our NOFO Builder retro with the coaches and HRSA.
We use the `application_deadline` field for the date that we have on the cover of the NOFO as well as the "Before you begin" page. However, it is also commonly in the body of the NOFO itself, usually inside of the "Key Dates" callout box.
If there is a change to the application date, writers have to hunt down all instances of this value and make sure they are all in sync.
The update here is to list them all on the edit page for the top-level `application_deadline` and offer to change them all at once.
**Note:** We don't have an …
=> Change all matched instances of application_deadline value

bloom_nofos/bloom_nofos/static/styles.css
I pushed some fixes back in https://github.com/HHS/simpler-grants-pdf-builder/pull/298, but it looks like it introduced 2 layout bugs:
1. The dot from the classname was always showing up. Now it only shows up if there _is_ a class on the th element.
2. Some overly general table CSS was forcing the last column of inline tables to be a 5% width, which was messing up my layouts.
Here are some screenshots:
|  dot `.` exists, and 5% width for last column       |   no dot, and last column looks normal    |
|    <img width="1021" alt="Screenshot 2025-04-30 at 1 44 47 PM" src="https://github.com/user-attachments/assets/a221a54b-6e1c-408c-aba8-62063f525b55" />    |  <img width="1021" alt="Screenshot 2025-04-30 at 1 44 06 PM" …
=> Fix 2 bugs with tables on nofo_edit page

CHANGELOG.md, Dockerfile
This PR rewrites our Dockerfile from the `-alpine` base to the `-slim` debian-based image.
Tested locally and things seem to be working fine. Let's see if the build pipeline holds up!
=> Rewrite Dockerfile for python:3.13-slim debian-based image

.dockerignore, CHANGELOG.md, Dockerfile, Makefile
This PR makes it possible to run our `make` commands with a docker image instead just natively. 
For example, we can build the image first and then call a command passing in our image name:
```
docker build -t pcraig3/bloom-nofos:dev .
make test USE_DOCKER=1 IMAGE_NAME=pcraig3/bloom-nofos:dev
```
Or we can use the `build` command if we want to use the default image name:
```
make build
make test USE_DOCKER=1
```
=> Makefile can now run as a docker container, not as a python app

CHANGELOG.md, bloom_nofos/nofos/management/commands/get_nofos_and_guides.py
This PR adds a script to download all NOFOs and Content Guides to a CSV. 
The primary motivator here is so that we can map between an old integer id and a new uuid, once we complete [the primary key migration](https://github.com/HHS/simpler-grants-pdf-builder/issues/305).
So this script will download all NOFOs and ContentGuides, and show us their id in one column and their uuid in another column, as well as other identifying attributes.
Run it like this:
> `poetry run python manage.py get_nofos_and_guides --output-file="nofos_content_guides.csv"`
The resulting CSV file will have column headings like this:
```
type | id | id_url | uuid | uuid_url | number | title | status | created | updated | archived
```
=> Add Django management script to get all NOFOs in a CSV

CHANGELOG.md, bloom_nofos/nofos/tests_nofos/test_utils.py, bloom_nofos/nofos/utils.py
This breaks the ability of the app to get PDFs, so not good.
The problem is that we changed the url pattern, so we started not allowing uuids to be permitted.
Previously, we were assuming integers but no longer.
=> Update match_view_url function to filter out non-uuid urls

CHANGELOG.md, Makefile
Very simple PR. 
When we build a docker image using the makefile (`make build`), they are now tagged with the latest git SHA.  If git is not available, this just tags them "latest"
Resolves: https://github.com/HHS/simpler-grants-gov/issues/4963
=> Tag Makefile-built docker images with the latest git SHA

CHANGELOG.md, bloom_nofos/bloom_nofos/static/theme-opdiv-ihs-white.css
This is a very simple PR. It changes our IHS link borders in the top nav to be white if they are not the current section. 
|    all link borders are blue, so it is hard to see the current one    |  now link borders are white, and only the current one is blue     |
|   <img width="1431" alt="Screenshot 2025-05-09 at 10 18 09 AM" src="https://github.com/user-attachments/assets/2400df3c-284f-4297-a2d9-ec072711681a" />     |    <img width="1431" alt="Screenshot 2025-05-09 at 10 17 36 AM" src="https://github.com/user-attachments/assets/922b1c75-f63d-4603-b2cb-115cfbdc3b1b" />   |
=> IHS top nav section links are white now

bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/bloom_nofos/templates/includes/alerts.html, bloom_nofos/nofos/views.py
This PR adds sticky alert functionality to the NOFO Builder, with auto-dismiss behavior and proper accessibility features. The alerts will stay at the top of the page while scrolling, auto-dismiss after 4 seconds, and can be manually dismissed. The implementation ensures proper keyboard navigation and screen reader support.
This update came from the need to keep alerts visible while users scroll through long NOFO documents, particularly when making edits or reviewing changes. The alerts now:
- Stay fixed at the top of the page while scrolling / auto-scrolling
- Auto-dismiss after 4 seconds with a fade animation
- Can be manually dismissed via a close button
- Support keyboard navigation and screen reader announcements
- Properly layer with other page elements through z-index management
- …
=> Fixed flash message after editing

bloom_nofos/bloom_nofos/static/styles.css, bloom_nofos/nofos/templates/nofos/nofo_edit_number.html, bloom_nofos/nofos/templates/nofos/nofo_edit_title.html, bloom_nofos/nofos/test_nofo.py, bloom_nofos/nofos/views.py
This PR modifies both the "Change NOFO Number" and "Change NOFO Title" views by showing all other subsections where these values exist and offering to change them all at the same time.
This story came out of our NOFO Builder retro with the coaches and HRSA.
We use the NOFO number and title fields for information that appears on the cover of the NOFO. However, these values are also commonly referenced throughout the body of the NOFO itself, such as in instructions or reference sections.
If there is a change to either the NOFO number or title, writers have to hunt down all instances of these values and make sure they are all in sync.
The update here is to list all instances on the respective edit pages for both the NOFO number and title, offering to change them all at once.
Note: We don't …
=> Change NOFO Number & Title Everywhere All At Once

CHANGELOG.md, nofos/nofos/nofo.py, nofos/nofos/test_nofo.py
This is a small PR that changes how we insert the `Important: public information` subsection. Instead of inserting it after the _first_ matching heading in Section 3, now we insert it into the _last_ matching heading. Essentially, we are just looping through subsections in reverse to find a match.
Since February, we have been injecting a new subsection (`Important: public information`) into step 3 of all Nofos: https://github.com/HHS/simpler-grants-pdf-builder/pull/96
It's generally been working as expected, until last week when we had a few ACF NOFOs come through where the "Public info" subsection was inserted right at the beginning of the section (it was 3rd in the list of subsections) and this confused everyone. This subsection is intended to come towards the end of Section 3, not at …
=> Add the "Important: public information" section after LAST matching subsection

nofos/bloom_nofos/urls.py, nofos/nofos/api/api.py, nofos/nofos/api/tests.py
Add a health check endpoint at `/api/health` that doesn't require auth.
We've decided to add this such that when the app is running, we can quickly check the status. This is in anticipation of running this within AWS.
Please note that this is _very_ simple and could be expanded to include checking the Database Connection too.
=> Added simple /health API endpoint

CHANGELOG.md, Dockerfile, nofos/nofos/api/api.py, nofos/nofos/api/tests.py
This PR adds `wget` to our Dockerfile and also allows the `HEAD` method for the `/health` endpoint.
The "healthcheck_command" in simpler-grants-gov is running `wget` inside of the container to check that the app is up and running.
This means we need to install wget as a Docker dependency.
Here's the command ([link](https://github.com/HHS/simpler-grants-gov/blob/ea2460fd5b83763f633b6f21ef51a09e873c515b/infra/modules/service/variables.tf#L178)):
- `wget --no-verbose --tries=1 --spider http://localhost:8000/health || exit 1`
Also, it's not immediately obvious, but the "--spider" option will send a `HEAD` request instead of a `GET` request:
So this PR also enables the "HEAD" method and also adds a test to confirm.
The way to test this PR is to run the `CMD-SHELL` inside of a docker container, …
=> Add wget for docker & support `HEAD` method for /health

CHANGELOG.md, Dockerfile
This PR adds a `db-migrate` command that we can execute from the root of the Dockerfile.
Inside of the GitHub action to deploy the nofos app, we have a database migration step:
- https://github.com/HHS/simpler-grants-gov/commit/b703d97e753f6aad8dff5c5d335f16b4396563e4
Which triggers command "make release-run-database-migrations":
- https://github.com/HHS/simpler-grants-gov/blob/main/Makefile#L278
Which calls ./bin/run-database-migrations
- https://github.com/HHS/simpler-grants-gov/blob/main/bin/run-database-migrations#L6
Which calls "db-migrate" command inside the container.
So this PR adds a `db-migrate` command when building the Dockerfile so that we can run migrations the same way that all the other apps do.
=> Add `db-migrate` command that can be run from built container

CHANGELOG.md, nofos/bloom_nofos/settings.py
When we are deploying the app inside of ECS, the containers use a dynamic private IP range starting with "10".
These can't be set in advance in env vars because they change, so we will now set them at runtime contingent on them being in a private IP range.
This is apparently how we can check our local ip inside of a docker container so that we can add it to `ALLOWED_HOSTS`.
Sources:
- https://stackoverflow.com/questions/37031749/django-allowed-hosts-ips-range
- https://code.djangoproject.com/ticket/27485
- https://medium.com/django-unleashed/djangos-allowed-hosts-in-aws-ecs-369959f2c2ab
=> Add current hostname IP to ALLOWED_HOSTS if inside private IP range (for ECR)

nofos/bloom_nofos/static/styles.css, nofos/bloom_nofos/templates/includes/alerts.html
[This PR addresses the comment to move the alert/success to the bottom of the NOFO Builder](https://github.com/HHS/simpler-grants-pdf-builder/issues/322#issuecomment-2880610918). It still has with auto-dismiss behavior and proper accessibility features. The alerts will stay at the **bottom** of the page while scrolling, auto-dismiss after 4 seconds, and can be manually dismissed. The implementation ensures proper keyboard navigation and screen reader support.
=> Updated id selector CSS + added animations for alert/success

CHANGELOG.md, nofos/bloom_nofos/settings.py, nofos/bloom_nofos/utils.py
This PR makes 2 changes:
1. Adds error checking to our `gethostbyname(gethostname())` call. 
2. Adds the Load Balancer DNS name to `ALLOWED_HOSTS` if it exists
These 2 changes will allow the container to run in non-Debug mode in AWS without using an "allow-everything" ALLOWED_HOSTS value of "*". 
They will also allow the app to run on Cory's laptop.
1. Adds error checking to our `gethostbyname(gethostname())` call.
Some people see an error when calling `gethostbyname(gethostname())`:
- https://stackoverflow.com/questions/39970606/gaierror-errno-8-nodename-nor-servname-provided-or-not-known-with-macos-sie
- https://github.com/zauberzeug/nicegui/issues/1178
We don't actually need to solve this error, we just need it to not crash. The point of this code is so that we can get our internal IP …
=> Update ALLOWED_HOSTS for AWS

nofos/nofos/views.py
Per [convo here](https://github.com/HHS/simpler-grants-pdf-builder/issues/331#issuecomment-2894435148), we are simply removing the <a> tag that was being rendered since we auto-scroll to the destination.
=> Bugfix - Remove Hyperlink for net-new subsection

poetry.lock, pyproject.toml
Doing this because there is a `Medium` vulnerability in 5.0.13 that is fixed in 5.0.14.
https://github.com/HHS/simpler-grants-gov/actions/runs/15147743231/job/42587548429?pr=5113
Note that we are not able to update to Django 5.1* or 5.2* yet because one of our libraries ([django-project-version](https://pypi.org/project/django-project-version/)), relies on < Django 5.1. Issue here: 
This PR does update Django to a new version but it doesn't get us onto the LTS version, so that's why I created this issue: https://github.com/HHS/simpler-grants-pdf-builder/issues/343
=> Update Django to 5.0.14

CHANGELOG.md, nofos/bloom_nofos/aws.py, nofos/bloom_nofos/db/backends/postgresql_iam/__init__.py, nofos/bloom_nofos/db/backends/postgresql_iam/base.py, nofos/bloom_nofos/settings.py
This PR updates our database wrapper to account for AWS' periodic token refreshing. The problem with the previous Database wrappers is that the password is set at the beginning and then never changed. AWS refreshes their password token every 15 minutes, so we need to be continually requesting new tokens when we reconnect.
Generally, when you set your database password, the value you set for "password" is static for the lifetime of the app that is running. Django has some settings around this (eg, [`CONN_MAX_AGE`](https://docs.djangoproject.com/en/5.2/ref/settings/#conn-max-age)), but they assume they will get a new connection with the same static variables. 
What we need to do when we connect to RDS is refresh the password periodically so that we are getting _new_ tokens, rather then …
=> Subclass Django's DatabaseWrapper backend for RDS

Dockerfile
Yesterday, we turned on container vulnerability scanning, and a few os-level packages [are being flagged](https://github.com/HHS/simpler-grants-gov/actions/runs/15171314960/job/42661896649).
This PR adds an explicit "upgrade" command for all 3 of them in our Dockerfile, which brings them up to the latest, "FIXED" versions.
This is what we are seeing in the vuln scan:
```
NAME     INSTALLED          FIXED-IN                TYPE    VULNERABILITY        SEVERITY
libcap2  1:2.66-4           1:2.66-4+deb12u1        deb     CVE-2025-1390        Medium
login    1:4.13+dfsg1-1+b1  1:4.13+dfsg1-1+deb12u1  deb     CVE-2023-4641        Medium
login    1:4.13+dfsg1-1+b1  1:4.13+dfsg1-1+deb12u1  deb     CVE-2023-29383       Low
passwd   1:4.13+dfsg1-1+b1  1:4.13+dfsg1-1+deb12u1  deb     CVE-2023-4641 …
```
=> Upgrade 3 debian libraries after results of vuln scan

Dockerfile
This commit adds a dedicated 'appuser' to the Docker image and switches to it before the application is started. 
This resolves the CIS-DI-0001 warning flagged by Dockle, which requires containers to avoid running as root.
Example here: https://github.com/HHS/simpler-grants-gov/actions/runs/15195040903/job/42737014418
By running as a non-root user:
- The container is less likely to be used as a pivot point in an attack
- Accidental or malicious writes to system paths are prevented
- Compliance scanners (e.g., Dockle, Trivy, etc.) pass with fewer flags
=> Create Dockerfile non-root user ("appuser") for container runtime

Dockerfile
This is breaking too many things.
It broke:
- our deploys
- linting in simpler-grants-gov
- db-migrate in simpler-grants-gov
I was hoping this would be a drop-in replacement but it didn't turn out that way.
=> Remove appuser from Docker container

CHANGELOG.md, nofos/nofos/templates/nofos/nofo_view.html
This is a small PR to override our template logic for one specific NOFO.
The idea is that we will show the "agency" name on the front cover instead of the "subagency" name for this one NOFO.
We can solve this with a real fix next week, but for now we just need to make this change.
=> Show agency name on front cover for HHS-2025-ACF-OCS-EF-0177

Dockerfile
We had a failing vuln report to do with 2 more debian libraries in our container.
```
NAME         INSTALLED         FIXED-IN          TYPE    VULNERABILITY  SEVERITY
libsystemd0  252.36-1~deb12u1  252.38-1~deb12u1  deb     CVE-2025-4598  Medium
libudev1     252.36-1~deb12u1  252.38-1~deb12u1  deb     CVE-2025-4598  Medium
```
Like before, we have a couple of libraries to upgrade.
=> Upgrade 2 more debian libraries after vuln scan

CHANGELOG.md, nofos/bloom_nofos/templates/includes/heading.html, nofos/nofos/templates/nofos/nofo_edit.html, nofos/nofos/templates/nofos/nofo_view.html, nofos/nofos/templates/nofos/subsection_edit.html, nofos/nofos/templatetags/safe_br.py, nofos/nofos/tests_nofos/test_templatetags.py
This is a fairly small PR that allows `<br>` tags in headings, which has been much requested by NOFO designers!!
This should work well for Subsections and Sections, although getting at Sections is harder (you have to use the admin UI).
| before | subsection_edit_view | after
|--------|-------|-------|
|   Textual widow, which is a word on its own line     |   Adding `<br>` tags directly    |  `<br>` tags are respected by the NOFO Builder  |
|   <img width="695" alt="Screenshot 2025-06-02 at 4 20 23 PM" src="https://github.com/user-attachments/assets/e44e30b6-0e98-4c22-ba06-7fd639b6e6ae" />     |    <img width="695" alt="Screenshot 2025-06-02 at 4 21 18 PM" src="https://github.com/user-attachments/assets/c5653624-fe37-4093-8106-35f5267c8e45" />  | <img width="695" alt="Screenshot …
=> Allow "<br>" tags in headings

Makefile
We want to be able to build production containers from the makefile so that we can deploy them this way in the simpler-grants-gov repo. 
In our repo, we run the tests without building the container. In the simpler-grants-gov repo, we build the container and then run the tests. This means, we need a version of the container for tests and a version that will be deployed.
=> Add IS_PROD_ARG to the build step in the Makefile

CHANGELOG.md, nofos/bloom_nofos/templates/index.html, nofos/users/templates/users/login.html, pyproject.toml
Add warning messages to the index page and the login page.
Now that we have different versions of the NOFO Builder, we want to prevent people from accidentally logging into the wrong one and doing a bunch of work in it. 
If people end up on ".dev" or ".rodeo" by accident, we want them to be able to figure out what is wrong and where to go.
| .rodeo | .dev |
|  YOU ARE ON THE WRONG WEBSITE<br>The NOFO Builder has moved.<br>To log in, go to nofos.simpler.grants.gov.      |  YOU ARE ON THE DEVELOPMENT SITE<br>This is a <strong>test</strong> version of the NOFO Builder.</br>Go to the live site at nofos.simpler.grants.gov.    |
|  <img width="1490" alt="Screenshot 2025-06-16 at 01 33 47" src="https://github.com/user-attachments/assets/88888796-979f-4d07-9c87-ef4b2409cfe6" /> …
=> Add warning message for ".rodeo" domain

CHANGELOG.md, nofos/nofos/nofo.py, nofos/nofos/test_nofo.py, nofos/nofos/tests_nofos/test_page_breaks.py, nofos/nofos/tests_nofos/test_utils.py, nofos/nofos/utils.py
This PR standardizes our highlighted text for our various 'search the nofo' functions. 
We search for things throughout the NOFO in 3 places now:
1. Find `nofo.title`, `nofo.number`, `nofo.application_deadline`
2. Find and replace button
3. Find page breaks
Previously, we would show you the _whole_ subsection with the highlighted text for (1) and (2), but the page_break view would show snippets of text only. 
It seemed like a good way to do things, so we are using that same logic around only showing the match and 100 characters before and after it. 
Now we have much smaller and cleaner looking find results!
Here is an example before and after of the title matching logic. 
- Before:
- After: 
|  all content in the subsection body is shown, given there …
=> Use same logic to extract highlighted text everywhere

CHANGELOG.md, nofos/nofos/templatetags/utils/__init__.py
Pretty simple PR: adds a new breadcrumb link for Sections called "Build your appliation"
|  "TODO" for (3)      |    "3. Build"    |
|     <img width="844" alt="Screenshot 2025-06-27 at 17 30 50" src="https://github.com/user-attachments/assets/d688d8d6-ff07-45bb-a2f4-bf911a240709" />   |    <img width="844" alt="Screenshot 2025-06-27 at 17 31 08" src="https://github.com/user-attachments/assets/0eeeedd0-8bfd-43d7-864e-30f9aab861b3" />   |
=> Add new nav breadcrumb for "Build your application"

CHANGELOG.md, nofos/nofos/templates/nofos/nofo_edit.html, nofos/nofos/views.py
- Add "Find & Replace" and "Remove Page Breaks" to 'in review' statuses (In review, paused, DOGE)
- Don't allow "Find & Replace" or "Remove Page Breaks" after publishing
- Rearrange views in views.py so that that similar functions are grouped together
Sort of a small change, but overall we want people to be able to edit nofos after they come back from review.
=> "Find & Replace" and "Remove Page Breaks" should be available for in review NOFOs

CHANGELOG.md, nofos/nofos/templatetags/replace_unicode_with_icon.py
If we have a list inside of a table cell, only the first icon was getting replaced. This code will make sure to replace all icons in the table cell.
Simple PR but the logic is pretty ugly to read through. Let's hope this is not a thing that happens very often.
|   Icons are _not_ replaced in 2nd column. It looks bad.     |  Icons in 2nd column _are_ replaced. It looks good.      |
|   <img width="685" height="468" alt="Screenshot 2025-07-14 at 20 02 58" src="https://github.com/user-attachments/assets/3b718017-228a-4a9c-ab68-3816f47d541f" />     |  <img width="685" height="468" alt="Screenshot 2025-07-14 at 20 01 52" src="https://github.com/user-attachments/assets/b46a7791-4e93-47e4-8f24-828c0a5d71fe" />     |
=> Replace more than 1 icon in a table cell

Dockerfile
Small PR to explicitly update libgnutls30 inside of Dockerfile.
This is to address identified vulnerability which was flagged by grype.
```
NAME         INSTALLED        FIXED IN         TYPE  VULNERABILITY   SEVERITY  EPSS %  RISK
libgnutls30  3.7.9-2+deb12u4  3.7.9-2+deb12u5  deb   CVE-2025-32990  Medium    18.55   < 0.1
libgnutls30  3.7.9-2+deb12u4  3.7.9-2+deb12u5  deb   CVE-2025-6395   Medium    16.40   < 0.1
libgnutls30  3.7.9-2+deb12u4  3.7.9-2+deb12u5  deb   CVE-2025-32988  Medium    16.26   < 0.1
libgnutls30  3.7.9-2+deb12u4  3.7.9-2+deb12u5  deb   CVE-2025-32989  Medium    3.87    < 0.1
```
=> Patch Dockerfile by updating libgnutls30

CHANGELOG.md, nofos/bloom_nofos/static/styles.css, nofos/bloom_nofos/templates/includes/side_navigation.html, nofos/nofos/nofo.py, nofos/nofos/templates/nofos/nofo_edit.html, nofos/nofos/templatetags/math_filters.py, nofos/nofos/test_nofo.py, nofos/nofos/tests_nofos/test_side_navigation.py, nofos/nofos/views.py
Refactored the side navigation component to use server-side rendering instead of client-side JavaScript population, improving performance and reliability.
- https://github.com/HHS/simpler-grants-pdf-builder/issues/278
- **Added `get_side_nav_links()` function** in `nofos/nofo.py` to generate navigation links based on NOFO sections
- **Updated `NofosEditView`** to pass `side_nav_headings` to template context
- **Created `math_filters.py`** template tag with `multiply` filter for dynamic height calculations
- **Enhanced side navigation template** to render navigation links and pipe characters server-side
- **Simplified JavaScript logic** by removing client-side navigation population
- **Added conditional rendering** to hide navigation when no sections exist
- **Added comprehensive tests** …
=> Improve side navigation functionality to NOFO editor

CHANGELOG.md, nofos/nofos/nofo.py, nofos/nofos/test_nofo.py, nofos/nofos/tests_nofos/test_side_navigation.py, nofos/nofos/tests_nofos/test_utils.py, nofos/nofos/utils.py
This PR updates our "Find and Replace" function so that it _can_ find URLs if your search term starts with a `#` or the string `http`. 
Previously, I excluded hrefs from the "Find and Replace" function with the supposition that it would be unintentional if people were replacing hrefs when they really wanted to just replace a word somewhere.
However, when people are explicitly looking for links (for example, if you have a NOFO with 10-15 broken links that all go to the same place) that you want to bulk update, this code turned out to be a nuisance. So the new rule is that if a search term starts with a `#` (for anchor links) or `http` (for external links), then we _will_ just look for everything in the text without excluding links. 
Tested it locally and it works just fine.
| before | …
=> Find + Replace function can now be used to replace href strings

nofos/bloom_nofos/settings.py, nofos/bloom_nofos/static/styles.css, nofos/bloom_nofos/templates/includes/alerts.html, nofos/bloom_nofos/urls.py, nofos/nofos/templates/nofos/nofo_edit.html, nofos/nofos/views.py, nofos/uploads/apps.py, nofos/uploads/templates/uploads/images.html, nofos/uploads/tests.py, nofos/uploads/urls.py, nofos/uploads/utils.py, nofos/uploads/views.py
This PR creates a new "uploads" app which lists images uploaded to our S3 bucket(s). It is only viewable by superusers and doesn't do anything right now other than list images that have been uploaded via the AWS console. 
This PR is setting us up for a near-future scenario where we want to allow users to upload their own cover images for NOFOs. 
Regular users shouldn't have access to this route, but superusers should be able to see uploaded images and which NOFOs they belong to. Maybe we want to introduce a "media library" at some point to let people pick from existing images, but for now that is off the table.
At this point, this route doesn't really do anything, instead it's meant to set the foundations for continuing with this story (eg, establishing that we can connect to the S3 …
=> Create "uploads" app to list images

nofos/bloom_nofos/s3/tests.py, nofos/bloom_nofos/s3/utils.py, nofos/bloom_nofos/static/styles.css, nofos/bloom_nofos/templates/includes/file_input.html, nofos/nofos/forms.py, nofos/nofos/nofo.py, nofos/nofos/templates/nofos/nofo_edit.html, nofos/nofos/templates/nofos/nofo_edit_cover_image.html, nofos/nofos/templates/nofos/nofo_upload_cover_image.html, nofos/nofos/test_nofo.py, nofos/nofos/urls.py, nofos/nofos/views.py, nofos/uploads/templates/uploads/images.html, nofos/uploads/views.py
This PR implements a comprehensive cover image upload and management system for NOFO (Notice of Funding Opportunity) documents. Users can now upload, replace, and remove cover images directly through the web interface, with all images stored securely in AWS S3.
- https://github.com/HHS/simpler-grants-pdf-builder/issues/93
- Secure file upload to AWS S3 with proper validation
- Support for PNG, JPG, and JPEG formats
- 5MB file size limit to ensure optimal performance
- Automatic file renaming based on NOFO short name
- Alt text support 
- One-click removal with confirmation modal
- Automatic cleanup from S3 storage
- Graceful fallback to default cover image
- Intuitive upload form with file selection and preview
- Modal confirmation dialogs for destructive actions
- Clear success/error …
=> Implement cover image upload and removal functionality

CHANGELOG.md, pyproject.toml
Very small PR to bumping the version number since the latest PR includes a migration, as is customary.
Updated CHANGELOG and bumped version to 3.6.0.
=> Bump version to 3.6.0

CHANGELOG.md, nofos/bloom_nofos/static/styles.css, nofos/bloom_nofos/templates/base.html
This PR is mercifully very small. It changes the header of the site to say "NOFO Boilerplate Compare", and the "All NOFOs" link to say "All content guides" which is in line with what the Figma mocks want.
There is a fairly crude bit of logic here such that we string match on "/guides". Could it potentially match an unintended URL in the future? Potentially. Could this be more elegant by using blocks a bit more? Maybe. Is it fine for user testing? For sure. It is easy and effective.
With this logic, any path that includes the string "/guides" has a new header that says "NOFO Boilerplate Compare", and also does not show the "LIVE"/"TEST" button.
Before and after views. Note that our site header is not really mobile (top links disappear) but that's fine. …
=> Change site header to say "NOFO Boilerplate Compare" for /guides URLs

CHANGELOG.md, nofos/bloom_nofos/static/styles.css, nofos/guides/templates/guides/guide_compare.html, nofos/guides/test_views.py, nofos/guides/urls.py, nofos/guides/views.py, nofos/nofos/nofo_compare.py, nofos/nofos/tests_nofos/test_compare.py
This PR adds a button to export your differences as a CSV. It also adds the backend view to do the export, so that we can build the CSV. Makes sense to do them both together like this. 
The CSV you can get after doing your comparison will change format depending on the exact comparison that you have. If there are no merged sections, then we will give you a CSV with these headings:
- `Status, Subsection name, Old value, New value`
However, if there are merged sections, then the subsection name has changed, so we need to include an extra column to show you that.
- `Status, Subsection name, Old value, New subsection name, New value`
So here is an example of each:
| 4-column CSV | 5-column CSV |
|  [compare-4-column.csv](https://github.com/user-attachments/files/21621120/con …
=> Add export CSV function to compare UI 

nofos/bloom_nofos/static/styles.css, nofos/nofos/templates/nofos/nofo_edit.html, nofos/nofos/templates/nofos/section_detail.html, nofos/nofos/views.py
This PR introduces two user experience improvements to the NOFO Builder:
1. **Status dropdown integration** - Change NOFO status directly from the edit page
2. **Table width checkbox** - Replace button with intuitive checkbox control
- https://github.com/HHS/simpler-grants-pdf-builder/issues/407
- Integrated status dropdown form into the NOFO edit template
- Updated view to pass status form to context
- Enhanced summary box with status-specific messages and actions
- Improves workflow efficiency by eliminating navigation to separate pages
| Before | After |
| --- | --- | 
|<img width="400" alt="1_draft" src="https://github.com/user-attachments/assets/aabf3ea1-26d7-4261-84ed-fbde6fd53928" /> | <img width="400" alt="1_draft_new" src="https://github.com/user-attachments/assets/30d350cc-c9e7-4 …
=> Table Width Checkbox and NOFO Status dropdown

nofos/guides/test_views.py, nofos/guides/views.py
This PR changes our CSV files to include the section name as the second column. 
Since we are wanting users to see the word "Sections" for our subsections, I called the section.name "Step name" and the subsection.name is a "Section name" now.
So, the old column headings looked like this:
```
Status, Subsection name, Old value, New value
```
And new ones look like this: 
```
Status, Step name, Section name, Old value, New value
```
=> Add Section ("Step") name to CSV output

nofos/bloom_nofos/static/styles.css, nofos/guides/templates/guides/guide_edit.html
- Added role="button" to links in the guide edit template for improved accessibility.
- Implemented logic to disable buttons when no sections are selected, enhancing user feedback with a warning message.
- Updated CSS to prevent pointer events on disabled links, ensuring a consistent user experience.
| Before | After | 
| --- | --- | 
| <img width="1096" height="1019" alt="Screenshot 2025-08-08 at 11 47 55 AM" src="https://github.com/user-attachments/assets/ce4ccb39-41d9-4ae7-9159-297e6511b667" /> | <img width="1063" height="1077" alt="Screenshot 2025-08-08 at 11 47 47 AM" src="https://github.com/user-attachments/assets/388b9bd5-bf66-4b99-bf93-48e0103f7036" /> |
=> Disabled buttons when no section/subsection selections are made in guide_edit page

CHANGELOG.md, nofos/guides/views.py, nofos/nofos/nofo_compare.py, nofos/nofos/tests_nofos/test_compare.py
This PR fixes the visual bug that we see when doing a compare of list items that the list with more elements creates empty list items on the other side. 
Now, empty list items are being stripped before being rendered.
When comparing two documents, the `<del>` tags signify everything that has been removed from the old document, and the `<ins>` tags represent everything that has been added in the new doc, stuff that was not in the original.
The point of this function is to decompose the 'combined' diff into 2 separate diffs, one which shows only deletions (the old doc) and one which shows only inserts (the new doc).
This is how we build out our side-by-side diff comparison UI.
However, there was technically a visual bug where some elements were entirely deleted or added:
- `<li><del>List …
=> Remove empty list items in NOFO Comparison screen

nofos/bloom_nofos/static/styles.css, nofos/guides/templates/guides/guide_compare.html, nofos/guides/templates/guides/guide_index.html, nofos/guides/templates/guides/subsection_edit.html, nofos/nofos/templates/nofos/nofo_edit.html, nofos/nofos/templates/nofos/nofo_edit_cover_image.html, nofos/nofos/templates/nofos/section_detail.html
There is a one visible change in this PR, which is adding trash bin icons for the "delete" column in the Content Guide index page.
There is also a non-visible change, which was reorganizing the icon buttons so that they are using more or less consistently applied classnames and styling. It saves us a few lines of code and makes our CSS file a little bit more manageable.
|  <img width="1450" height="991" alt="Screenshot 2025-08-13 at 19 21 26" src="https://github.com/user-attachments/assets/e986fb15-ea90-4a38-8388-0ccdfe5c055f" />      |   <img width="1450" height="991" alt="Screenshot 2025-08-13 at 19 21 04" src="https://github.com/user-attachments/assets/adde0f9f-1d06-46d6-8295-b21fd589bef6" />    |
=> Add delete icon for Content Guides index page

CHANGELOG.md, nofos/bloom_nofos/static/theme-base.css, nofos/bloom_nofos/static/theme-orientation-portrait.css, nofos/nofos/templates/nofos/nofo_view.html
This PR makes 3 changes to our NOFO rendering:
- Alignment fixes for checklist layout when Application Checklist tables are in Step 3
- Reduces the very large heading sizes in Appendices
- Make the "Have questions?" box inline when we are not in Step 1
We have added a lot of very specific CSS to fix the application tables, which is bad and I hate.
Luckily, we are trying to improve them this time around, using 3 simple tables instead of one big omni-table. 
However, there are some growing pains here as not all my CSS is applying in the right places.
|  checkboxes are vertically higher than text. extra left padding in second table.      |  checkboxes and text are vertically centred. no weird left padding issues in second table.     |
|  <img width="844" …
=> Fixes for Application Checklist in Step 3

CHANGELOG.md, nofos/bloom_nofos/static/theme-base.css, nofos/nofos/nofo.py, nofos/nofos/test_nofo.py, nofos/nofos/tests_nofos/test_page_breaks.py
This PR makes our `add_page_breaks_to_headings` method look for section names as well as the subsection name.
We used to just always add the heading class to the subsections as long as they matched our hardcoded names (eg, "Application checklist). However, in the new version of the content guide, "Application checklist" should not have a new page break when it is on step 3.
But we _do_ want to still add the page break when it is in Step 5.
Also fixes some tests to account for new logic.
|     Page break automatically injected   |  Page break is not injected anymore     |
|   <img width="917" height="720" alt="Screenshot 2025-08-21 at 12 13 13" src="https://github.com/user-attachments/assets/139446cb-1e8c-4b75-97d3-3807c517e582" />     |   <img …
=> add_page_breaks_to_headings function now checks for section name

documentation/adr/2025-07-23-html-diffing-library.md
This PR updates the `HTML diffing library` Architecture Decision Record to outline what we _actually_ ended up doing. It is purely a documentation update and makes no functional changes to the app.
=> Correct the ADR for our diffing library

CHANGELOG.md, nofos/bloom_nofos/static/theme-base.css, nofos/nofos/views.py, pyproject.toml
We are using DocRaptor for our PDF printing, and "pipeline" version 11 is the latest one (still undocumented, at the time of writing), which brings in Prince version 16.
Upgrading our version of Prince allows us to automatically tag H7s in the PDF, and then map them to paragraph tags. Check out Prince's documentation on this here: https://www.princexml.com/doc/prince-output/#pdf-tags
The only visual change I have picked up on is that table borders are 'open' by default instead of 'closed' where table cells continue onto the next page.
| Prince v15 vs v16  |
|--------------|
|       <img width="2540" height="1396" alt="Screenshot 2025-08-22 at 12 23 19" src="https://github.com/user-attachments/assets/6662d123-8fb1-4638-a65f-55e7a4fbe665" />      |
After talking with one of Prince's devs, …
=> Update version of Prince we use to generate PDFs

CHANGELOG.md, nofos/bloom_nofos/static/theme-base.css
This PR makes a CSS change to remove a white outline that is unexpectedly showing up in our PDF output since upgrading the Prince version in #456.
This CSS rule makes no visible difference in the HTML rendering, but in the new version of Prince, it results in a white outline around table headings that we don't think should be there.
So let's remove it. It seems like is not doing anything useful for us but it _is_ causing problems.
|   Grey border, then _white outline_ (bad), then blue background     |  Grey border, white outline     |
|    <img width="2760" height="3022" alt="Screenshot 2025-09-05 at 19 14 09" src="https://github.com/user-attachments/assets/a1c16d80-e3c1-467f-b199-63683e314c24" />    |    <img width="2762" height="3022" …
=> Remove white outline in table headings in PDF

CHANGELOG.md, nofos/bloom_nofos/static/js/nofos/nofo_edit.js, nofos/bloom_nofos/static/shared.css, nofos/bloom_nofos/static/styles.css, nofos/nofos/templates/nofos/nofo_edit.html
This PR moves the "Top" button to the bottom-right of the screen instead of in the sticky table headers we hav had them in so far.
It also updates the CHANGELOG to detail what we have shipped so far as part of the Header UI updates.
This is a continuation of #460 
In the `nofo_edit` page, we previously had all the "back to top" buttons in the right hand side of the sticky headings of the NOFO section table headings.
This was kind of a weird place for them, as their placement would slightly change as you were editing (there could be 2 "top" links on the same screen, for example).
New top link is stuck to the bottom. It will:
- float on the bottom-right of the screen
- appear after you scroll past the (visually hidden) "back-to-top--sentinel" element
- disappear when you scroll up and it …
=> Move "Top" button to bottom-right
